/**
 * 全局错误码常量
 */

export const ERROR_CODE = {
  // 通用
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,

  // 业务 - 用户
  USER_EXISTS: 4001,
  USER_NOT_FOUND: 4002,
  PASSWORD_WRONG: 4003,
  TOKEN_EXPIRED: 4004,
  TOKEN_INVALID: 4005,
  ACCOUNT_DISABLED: 4006,
  EC_AUTH_002: 4007,      // Access Token 过期，前端应自动刷新
  REFRESH_TOKEN_EXPIRED: 4008,
  REFRESH_TOKEN_INVALID: 4009,

  // 业务 - 资源
  RESOURCE_NOT_FOUND: 4101,
  RESOURCE_DUPLICATE: 4102,
  QUOTA_EXCEEDED: 4103,

  // 业务 - 参数
  PARAM_MISSING: 4201,
  PARAM_INVALID: 4202,
  PARAM_ERROR: 4203,
  VALIDATION_ERROR: 4901, // Zod schema 校验失败

  // 业务 - 支付
  PAY_ORDER_NOT_FOUND: 4301,
  PAY_ORDER_EXPIRED: 4302,
  PAY_SIGN_FAILED: 4303,
  PAY_CHANNEL_ERROR: 4304,
  PAY_AMOUNT_MISMATCH: 4305,
  PAY_NOTIFY_FAILED: 4306,

  // 业务 - 内容审核
  CONTENT_MODERATION: 4401,

  // 业务 - 发布校验
  PUBLISH_VALIDATION: 4402,
};

export const ERROR_MSG = {
  [ERROR_CODE.BAD_REQUEST]: '请求参数错误',
  [ERROR_CODE.UNAUTHORIZED]: '未登录或登录已过期',
  [ERROR_CODE.PAYMENT_REQUIRED]: '需付费购买',
  [ERROR_CODE.FORBIDDEN]: '无访问权限',
  [ERROR_CODE.NOT_FOUND]: '资源不存在',
  [ERROR_CODE.INTERNAL_ERROR]: '服务器内部异常',

  [ERROR_CODE.USER_EXISTS]: '用户已存在',
  [ERROR_CODE.USER_NOT_FOUND]: '用户不存在',
  [ERROR_CODE.PASSWORD_WRONG]: '密码错误',
  [ERROR_CODE.TOKEN_EXPIRED]: 'Token 已过期',
  [ERROR_CODE.TOKEN_INVALID]: 'Token 无效',
  [ERROR_CODE.ACCOUNT_DISABLED]: '账号已被禁用',
  [ERROR_CODE.EC_AUTH_002]: 'Access Token 已过期',
  [ERROR_CODE.REFRESH_TOKEN_EXPIRED]: 'Refresh Token 已过期',
  [ERROR_CODE.REFRESH_TOKEN_INVALID]: 'Refresh Token 无效',

  [ERROR_CODE.RESOURCE_NOT_FOUND]: '资源不存在',
  [ERROR_CODE.RESOURCE_DUPLICATE]: '资源重复',
  [ERROR_CODE.QUOTA_EXCEEDED]: '配额已用尽',

  [ERROR_CODE.PARAM_MISSING]: '缺少必要参数',
  [ERROR_CODE.PARAM_INVALID]: '参数格式错误',
  [ERROR_CODE.PARAM_ERROR]: '参数错误',

  [ERROR_CODE.PAY_ORDER_NOT_FOUND]: '支付订单不存在',
  [ERROR_CODE.PAY_ORDER_EXPIRED]: '支付订单已过期',
  [ERROR_CODE.PAY_SIGN_FAILED]: '签名验证失败',
  [ERROR_CODE.PAY_CHANNEL_ERROR]: '支付渠道错误',
  [ERROR_CODE.PAY_AMOUNT_MISMATCH]: '支付金额不匹配',
  [ERROR_CODE.PAY_NOTIFY_FAILED]: '支付回调处理失败',
};
