-- B2 提示词模板种子数据（100+ 电商预设）
-- 8 分类: main_image / scene / video / script / copy / viral-clone / translate / creative

-- ==================== 1. main_image 主图模板 (20个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id, tags, difficulty) VALUES
('TPL_MAIN_001', 'main_image', '电商通用主图', '适用于服装、饰品等白底商品主图生成', '为{{product_name}}生成高质量商品主图：\n1. 纯白背景，{{product_name}}位于画面{{position}}\n2. {{lighting}}布光，突出商品质感\n3. 分辨率2048x2048，细节清晰\n4. 风格：{{style}}', '[{"name":"product_name","label":"商品名称","type":"text","required":true,"placeholder":"如：夏季连衣裙"},{"name":"position","label":"商品位置","type":"select","options":["居中","偏左","偏右"]},{"name":"lighting","label":"灯光风格","type":"select","options":["柔光","硬光","侧光","环形光"]},{"name":"style","label":"整体风格","type":"select","options":["简约","时尚","奢华","清新","科技感"]}]', 'image', 'star', 100, 1, 2, 128, 1, '通用,白底,入门', 1),

('TPL_MAIN_002', 'main_image', '美妆产品主图', '护肤品、化妆品专用，突出光泽质感', '为{{product_name}}生成电商主图。{{product_name}}是一款{{product_type}}，主打{{selling_point}}。\n渐变背景({{bg_color}})，产品居中，突出{{texture}}质感。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：保湿精华液"},{"name":"product_type","label":"产品类型","type":"text","required":true,"placeholder":"如：精华/面霜/口红"},{"name":"selling_point","label":"卖点","type":"text","required":true,"placeholder":"如：深层补水"},{"name":"bg_color","label":"背景色系","type":"select","options":["粉色渐变","蓝色渐变","金色渐变","紫色渐变","绿色渐变"]},{"name":"texture","label":"质感","type":"select","options":["水润光泽","哑光高级","晶莹剔透","丝绒柔焦"]}]', 'image', 'palette', 95, 1, 2, 86, 1, '美妆,护肤,化妆品', 1),

('TPL_MAIN_003', 'main_image', '3C数码产品主图', '手机壳、耳机、充电宝等科技产品', '为{{product_name}}生成科技感产品主图。{{bg_style}}背景，{{product_name}}{{display_mode}}展示，搭配{{light_effect}}光效，突出{{highlight}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg_style","label":"背景风格","type":"select","options":["深色科技","纯白简约","渐变霓虹","金属拉丝"]},{"name":"display_mode","label":"展示方式","type":"select","options":["悬浮","手持","平铺","爆炸图"]},{"name":"light_effect","label":"光效","type":"select","options":["霓虹灯","粒子光效","激光线条","简约光晕","镜面反射"]},{"name":"highlight","label":"重点突出","type":"select","options":["整体外观","接口细节","材质纹理","尺寸对比"]}]', 'image', 'cpu', 90, 1, 2, 72, 1, '3C,数码,科技', 2),

('TPL_MAIN_004', 'main_image', '鞋靴产品主图', '运动鞋、皮鞋、靴子等鞋类专用', '为{{product_name}}生成鞋类主图。{{angle}}拍摄角度，{{bg_type}}背景，突出{{feature}}，鞋底{{sole_display}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：飞织跑鞋"},{"name":"angle","label":"拍摄角度","type":"select","options":["45度侧面","正面","后跟特写","俯拍","动态悬浮"]},{"name":"bg_type","label":"背景类型","type":"select","options":["纯白","渐变灰","场景地面","动态速度线"]},{"name":"feature","label":"突出特点","type":"select","options":["鞋面材质","鞋底科技","整体流线","细节缝线"]},{"name":"sole_display","label":"鞋底展示","type":"select","options":["不展示","侧翻展示","独立底图"]}]', 'image', 'footprints', 88, 1, 2, 58, 1, '鞋靴,运动,时尚', 1),

('TPL_MAIN_005', 'main_image', '食品饮料主图', '零食、饮品、生鲜等食品类商品', '为{{product_name}}生成食品主图。{{scene}}场景，{{lighting}}光线，画面{{mood}}，{{product_name}}呈现{{texture}}质感，{{garnish}}搭配点缀。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：手工曲奇饼干"},{"name":"scene","label":"场景","type":"select","options":["木质餐桌","大理石台面","野餐布","吧台","纯色背景"]},{"name":"lighting","label":"光线","type":"select","options":["自然窗光","暖色侧光","柔光箱","逆光氛围"]},{"name":"mood","label":"画面氛围","type":"select","options":["温暖治愈","清新自然","高端精致","食欲爆棚"]},{"name":"texture","label":"质感","type":"select","options":["酥脆","绵软","晶莹","浓郁"]},{"name":"garnish","label":"搭配点缀","type":"text","required":false,"placeholder":"如：咖啡豆、薄荷叶"}]', 'image', 'coffee', 85, 1, 2, 94, 1, '食品,饮料,生鲜', 2),

('TPL_MAIN_006', 'main_image', '珠宝首饰主图', '项链、戒指、耳环等珠宝产品', '为{{product_name}}生成珠宝主图。{{metal_type}}材质，{{gem}}宝石，{{bg}}背景，{{light_setup}}布光方案，突出{{focus}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：18K金钻石项链"},{"name":"metal_type","label":"金属类型","type":"select","options":["黄金","白金","玫瑰金","铂金","银"]},{"name":"gem","label":"宝石类型","type":"text","required":false,"placeholder":"如：钻石、蓝宝石"},{"name":"bg","label":"背景","type":"select","options":["黑色丝绒","白色大理石","镜面反射","渐变丝绸"]},{"name":"light_setup","label":"布光方案","type":"select","options":["三点布光","环形微距光","星光特效","柔光漫反射"]},{"name":"focus","label":"焦点","type":"select","options":["火彩折射","金属质感","整体造型","细节工艺"]}]', 'image', 'gem', 82, 1, 2, 45, 1, '珠宝,首饰,奢侈品', 3),

('TPL_MAIN_007', 'main_image', '服装平铺主图', '服装平铺拍摄，展示版型和细节', '{{product_name}}平铺拍摄。{{layout}}摆放，{{fold_style}}折叠方式，{{lighting}}光线，展示{{show_detail}}细节，{{prop}}道具点缀。', '[{"name":"product_name","label":"服装名称","type":"text","required":true},{"name":"layout","label":"摆放方式","type":"select","options":["完全平铺","半折叠","悬挂展示","卷起一角"]},{"name":"fold_style","label":"折叠风格","type":"select","options":["简约折叠","日式叠法","随意褶皱","立体展示"]},{"name":"show_detail","label":"展示细节","type":"select","options":["领口设计","袖口工艺","面料纹理","印花图案"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：干花、杂志"}]', 'image', 'shirt', 80, 1, 2, 38, 1, '服装,平铺,版型', 2),

('TPL_MAIN_008', 'main_image', '箱包皮具主图', '手提包、背包、钱包等皮具产品', '{{product_name}}{{color}}色{{style}}款。{{angle}}拍摄，{{bg}}背景，展示{{detail}}，体现{{texture}}质感。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：真皮手提包"},{"name":"color","label":"颜色","type":"text","required":true,"placeholder":"如：棕色"},{"name":"style","label":"款式","type":"select","options":["商务","休闲","时尚","复古","极简"]},{"name":"angle","label":"拍摄角度","type":"select","options":["正面","45度","顶部","侧面","内部展示"]},{"name":"bg","label":"背景","type":"select","options":["纯白","原木色","灰色渐变","生活场景"]},{"name":"detail","label":"展示细节","type":"select","options":["五金件","缝线","内里","整体造型"]},{"name":"texture","label":"皮质质感","type":"select","options":["荔枝纹","光滑牛皮","哑光磨砂","鳄鱼纹"]}]', 'image', 'briefcase', 78, 1, 2, 33, 1, '箱包,皮具,配饰', 2),

('TPL_MAIN_009', 'main_image', '家居用品主图', '床上用品、厨具、装饰品等', '{{product_name}}主图。{{room}}场景，{{style}}风格，{{time}}光线，{{product_name}}作为{{role}}呈现。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"room","label":"房间类型","type":"select","options":["卧室","厨房","客厅","浴室","阳台"]},{"name":"style","label":"装修风格","type":"select","options":["北欧简约","日式原木","现代轻奢","美式复古","极简白"]},{"name":"time","label":"光线时间","type":"select","options":["早晨自然光","午后暖阳","傍晚暖黄","室内灯光"]},{"name":"role","label":"产品角色","type":"select","options":["画面主角","场景点缀","功能展示","对比展示"]}]', 'image', 'home', 76, 1, 2, 41, 1, '家居,生活,装饰', 1),

('TPL_MAIN_010', 'main_image', '母婴产品主图', '婴儿用品、玩具、童装等', '为{{product_name}}生成母婴产品主图。{{bg}}背景，色调{{tone}}，{{prop}}搭配，营造{{mood}}氛围，强调{{safety}}安全性。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["纯白","柔和粉色","浅蓝","奶油色","木纹"]},{"name":"tone","label":"色调","type":"select","options":["马卡龙色系","莫兰迪色系","自然大地色","明亮暖色"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：毛绒玩具、木质积木"},{"name":"mood","label":"氛围","type":"select","options":["温馨可爱","安全纯净","活泼趣味","高端质感"]},{"name":"safety","label":"安全标识","type":"select","options":["材质特写","认证标识角标","圆角设计展示","无毒标识"]}]', 'image', 'baby', 74, 1, 2, 29, 1, '母婴,婴儿,安全', 2),

-- main_image continue 11-20
('TPL_MAIN_011', 'main_image', '运动户外主图', '健身器材、户外装备等', '{{product_name}}运动场景主图。{{env}}环境，{{action}}动作状态，{{light}}光线，展示{{feature}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"env","label":"环境","type":"select","options":["健身房","户外跑道","山地","泳池","瑜伽室"]},{"name":"action","label":"使用状态","type":"select","options":["静态展示","动态使用","细节特写","对比展示"]},{"name":"light","label":"光线","type":"select","options":["自然日光","室内灯光","清晨逆光","黄昏侧光"]},{"name":"feature","label":"突出特点","type":"select","options":["材质科技","人体工学","便携设计","防水性能"]}]', 'image', 'dumbbell', 72, 1, 2, 35, 1, '运动,户外,健身', 2),

('TPL_MAIN_012', 'main_image', '宠物用品主图', '宠物食品、玩具、窝具等', '{{product_name}}宠物产品主图。{{pet_type}}使用场景，{{bg}}背景，展示{{feature}}，画面{{mood}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"pet_type","label":"适用宠物","type":"select","options":["猫","狗","小型宠物","水族"]},{"name":"bg","label":"背景","type":"select","options":["家庭场景","户外草地","纯色背景","宠物使用实景"]},{"name":"feature","label":"突出特点","type":"select","options":["天然成分","耐用设计","趣味互动","舒适材质"]},{"name":"mood","label":"画面氛围","type":"select","options":["活泼欢乐","温馨治愈","高端专业","自然清新"]}]', 'image', 'paw', 70, 1, 2, 28, 1, '宠物,猫狗,用品', 1),

('TPL_MAIN_013', 'main_image', '汽车用品主图', '车载配件、养护产品等', '{{product_name}}汽车用品主图。{{bg}}背景，{{angle}}角度，展示{{feature}}，体现{{style}}风格。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["车内实景","纯黑科技","车库场景","户外公路"]},{"name":"angle","label":"角度","type":"select","options":["产品特写","安装效果","使用场景","对比展示"]},{"name":"feature","label":"突出特点","type":"select","options":["材质质感","安装便捷","科技功能","安全防护"]},{"name":"style","label":"风格","type":"select","options":["极简科技","硬核专业","高端奢华","实用主义"]}]', 'image', 'car', 68, 1, 2, 22, 1, '汽车,车载,配件', 2),

('TPL_MAIN_014', 'main_image', '图书文具主图', '书籍、文具、办公用品等', '{{product_name}}主图。{{layout}}构图，{{bg}}背景，{{prop}}搭配，{{light}}光线，体现{{style}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"layout","label":"构图","type":"select","options":["平铺俯拍","45度陈列","手持展示","场景融入"]},{"name":"bg","label":"背景","type":"select","options":["纯白","木质桌面","大理石","织物纹理"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：咖啡杯、绿植"},{"name":"light","label":"光线","type":"select","options":["窗边自然光","暖色台灯","柔光箱","侧逆光"]},{"name":"style","label":"风格","type":"select","options":["文艺清新","极简商务","复古质感","日系治愈"]}]', 'image', 'book', 66, 1, 2, 19, 1, '图书,文具,办公', 1),

('TPL_MAIN_015', 'main_image', '节庆礼品主图', '节日礼品、礼盒、贺卡等', '{{product_name}}节庆礼品主图。{{holiday}}主题，{{color_scheme}}配色，{{decoration}}装饰元素，{{mood}}氛围。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"holiday","label":"节日","type":"select","options":["春节","情人节","母亲节","中秋节","圣诞节","元旦"]},{"name":"color_scheme","label":"配色方案","type":"select","options":["中国红+金","粉色+白","暖橙+棕","深蓝+银","绿+红"]},{"name":"decoration","label":"装饰元素","type":"text","required":false,"placeholder":"如：丝带、灯串、花瓣"},{"name":"mood","label":"氛围","type":"select","options":["喜庆热闹","浪漫温馨","感恩暖心","团圆美满"]}]', 'image', 'gift', 64, 1, 2, 31, 1, '节日,礼品,礼盒', 2),
