-- B2 提示词模板种子数据（100+ 电商预设）
-- 8 分类: main_image / scene / video / script / copy / viral-clone / translate / creative

-- ==================== 1. main_image 主图模板 (20个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_MAIN_001', 'main_image', '电商通用主图', '适用于服装、饰品等白底商品主图生成', '为{{product_name}}生成高质量商品主图：\n1. 纯白背景，{{product_name}}位于画面{{position}}\n2. {{lighting}}布光，突出商品质感\n3. 分辨率2048x2048，细节清晰\n4. 风格：{{style}}', '[{"name":"product_name","label":"商品名称","type":"text","required":true,"placeholder":"如：夏季连衣裙"},{"name":"position","label":"商品位置","type":"select","options":["居中","偏左","偏右"]},{"name":"lighting","label":"灯光风格","type":"select","options":["柔光","硬光","侧光","环形光"]},{"name":"style","label":"整体风格","type":"select","options":["简约","时尚","奢华","清新","科技感"]}]', 'image', 'star', 100, 1, 2, 128, 1),

('TPL_MAIN_002', 'main_image', '美妆产品主图', '护肤品、化妆品专用，突出光泽质感', '为{{product_name}}生成电商主图。{{product_name}}是一款{{product_type}}，主打{{selling_point}}。\n渐变背景({{bg_color}})，产品居中，突出{{texture}}质感。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：保湿精华液"},{"name":"product_type","label":"产品类型","type":"text","required":true,"placeholder":"如：精华/面霜/口红"},{"name":"selling_point","label":"卖点","type":"text","required":true,"placeholder":"如：深层补水"},{"name":"bg_color","label":"背景色系","type":"select","options":["粉色渐变","蓝色渐变","金色渐变","紫色渐变","绿色渐变"]},{"name":"texture","label":"质感","type":"select","options":["水润光泽","哑光高级","晶莹剔透","丝绒柔焦"]}]', 'image', 'palette', 95, 1, 2, 86, 1),

('TPL_MAIN_003', 'main_image', '3C数码产品主图', '手机壳、耳机、充电宝等科技产品', '为{{product_name}}生成科技感产品主图。{{bg_style}}背景，{{product_name}}{{display_mode}}展示，搭配{{light_effect}}光效，突出{{highlight}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg_style","label":"背景风格","type":"select","options":["深色科技","纯白简约","渐变霓虹","金属拉丝"]},{"name":"display_mode","label":"展示方式","type":"select","options":["悬浮","手持","平铺","爆炸图"]},{"name":"light_effect","label":"光效","type":"select","options":["霓虹灯","粒子光效","激光线条","简约光晕","镜面反射"]},{"name":"highlight","label":"重点突出","type":"select","options":["整体外观","接口细节","材质纹理","尺寸对比"]}]', 'image', 'cpu', 90, 1, 2, 72, 1),

('TPL_MAIN_004', 'main_image', '鞋靴产品主图', '运动鞋、皮鞋、靴子等鞋类专用', '为{{product_name}}生成鞋类主图。{{angle}}拍摄角度，{{bg_type}}背景，突出{{feature}}，鞋底{{sole_display}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：飞织跑鞋"},{"name":"angle","label":"拍摄角度","type":"select","options":["45度侧面","正面","后跟特写","俯拍","动态悬浮"]},{"name":"bg_type","label":"背景类型","type":"select","options":["纯白","渐变灰","场景地面","动态速度线"]},{"name":"feature","label":"突出特点","type":"select","options":["鞋面材质","鞋底科技","整体流线","细节缝线"]},{"name":"sole_display","label":"鞋底展示","type":"select","options":["不展示","侧翻展示","独立底图"]}]', 'image', 'footprints', 88, 1, 2, 58, 1),

('TPL_MAIN_005', 'main_image', '食品饮料主图', '零食、饮品、生鲜等食品类商品', '为{{product_name}}生成食品主图。{{scene}}场景，{{lighting}}光线，画面{{mood}}，{{product_name}}呈现{{texture}}质感，{{garnish}}搭配点缀。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：手工曲奇饼干"},{"name":"scene","label":"场景","type":"select","options":["木质餐桌","大理石台面","野餐布","吧台","纯色背景"]},{"name":"lighting","label":"光线","type":"select","options":["自然窗光","暖色侧光","柔光箱","逆光氛围"]},{"name":"mood","label":"画面氛围","type":"select","options":["温暖治愈","清新自然","高端精致","食欲爆棚"]},{"name":"texture","label":"质感","type":"select","options":["酥脆","绵软","晶莹","浓郁"]},{"name":"garnish","label":"搭配点缀","type":"text","required":false,"placeholder":"如：咖啡豆、薄荷叶"}]', 'image', 'coffee', 85, 1, 2, 94, 1),

('TPL_MAIN_006', 'main_image', '珠宝首饰主图', '项链、戒指、耳环等珠宝产品', '为{{product_name}}生成珠宝主图。{{metal_type}}材质，{{gem}}宝石，{{bg}}背景，{{light_setup}}布光方案，突出{{focus}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：18K金钻石项链"},{"name":"metal_type","label":"金属类型","type":"select","options":["黄金","白金","玫瑰金","铂金","银"]},{"name":"gem","label":"宝石类型","type":"text","required":false,"placeholder":"如：钻石、蓝宝石"},{"name":"bg","label":"背景","type":"select","options":["黑色丝绒","白色大理石","镜面反射","渐变丝绸"]},{"name":"light_setup","label":"布光方案","type":"select","options":["三点布光","环形微距光","星光特效","柔光漫反射"]},{"name":"focus","label":"焦点","type":"select","options":["火彩折射","金属质感","整体造型","细节工艺"]}]', 'image', 'gem', 82, 1, 2, 45, 1),

('TPL_MAIN_007', 'main_image', '服装平铺主图', '服装平铺拍摄，展示版型和细节', '{{product_name}}平铺拍摄。{{layout}}摆放，{{fold_style}}折叠方式，{{lighting}}光线，展示{{show_detail}}细节，{{prop}}道具点缀。', '[{"name":"product_name","label":"服装名称","type":"text","required":true},{"name":"layout","label":"摆放方式","type":"select","options":["完全平铺","半折叠","悬挂展示","卷起一角"]},{"name":"fold_style","label":"折叠风格","type":"select","options":["简约折叠","日式叠法","随意褶皱","立体展示"]},{"name":"show_detail","label":"展示细节","type":"select","options":["领口设计","袖口工艺","面料纹理","印花图案"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：干花、杂志"}]', 'image', 'shirt', 80, 1, 2, 38, 1),

('TPL_MAIN_008', 'main_image', '箱包皮具主图', '手提包、背包、钱包等皮具产品', '{{product_name}}{{color}}色{{style}}款。{{angle}}拍摄，{{bg}}背景，展示{{detail}}，体现{{texture}}质感。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：真皮手提包"},{"name":"color","label":"颜色","type":"text","required":true,"placeholder":"如：棕色"},{"name":"style","label":"款式","type":"select","options":["商务","休闲","时尚","复古","极简"]},{"name":"angle","label":"拍摄角度","type":"select","options":["正面","45度","顶部","侧面","内部展示"]},{"name":"bg","label":"背景","type":"select","options":["纯白","原木色","灰色渐变","生活场景"]},{"name":"detail","label":"展示细节","type":"select","options":["五金件","缝线","内里","整体造型"]},{"name":"texture","label":"皮质质感","type":"select","options":["荔枝纹","光滑牛皮","哑光磨砂","鳄鱼纹"]}]', 'image', 'briefcase', 78, 1, 2, 33, 1),

('TPL_MAIN_009', 'main_image', '家居用品主图', '床上用品、厨具、装饰品等', '{{product_name}}主图。{{room}}场景，{{style}}风格，{{time}}光线，{{product_name}}作为{{role}}呈现。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"room","label":"房间类型","type":"select","options":["卧室","厨房","客厅","浴室","阳台"]},{"name":"style","label":"装修风格","type":"select","options":["北欧简约","日式原木","现代轻奢","美式复古","极简白"]},{"name":"time","label":"光线时间","type":"select","options":["早晨自然光","午后暖阳","傍晚暖黄","室内灯光"]},{"name":"role","label":"产品角色","type":"select","options":["画面主角","场景点缀","功能展示","对比展示"]}]', 'image', 'home', 76, 1, 2, 41, 1),

('TPL_MAIN_010', 'main_image', '母婴产品主图', '婴儿用品、玩具、童装等', '为{{product_name}}生成母婴产品主图。{{bg}}背景，色调{{tone}}，{{prop}}搭配，营造{{mood}}氛围，强调{{safety}}安全性。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["纯白","柔和粉色","浅蓝","奶油色","木纹"]},{"name":"tone","label":"色调","type":"select","options":["马卡龙色系","莫兰迪色系","自然大地色","明亮暖色"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：毛绒玩具、木质积木"},{"name":"mood","label":"氛围","type":"select","options":["温馨可爱","安全纯净","活泼趣味","高端质感"]},{"name":"safety","label":"安全标识","type":"select","options":["材质特写","认证标识角标","圆角设计展示","无毒标识"]}]', 'image', 'baby', 74, 1, 2, 29, 1),

('TPL_MAIN_011', 'main_image', '运动户外主图', '健身器材、户外装备等', '{{product_name}}运动场景主图。{{env}}环境，{{action}}动作状态，{{light}}光线，展示{{feature}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"env","label":"环境","type":"select","options":["健身房","户外跑道","山地","泳池","瑜伽室"]},{"name":"action","label":"使用状态","type":"select","options":["静态展示","动态使用","细节特写","对比展示"]},{"name":"light","label":"光线","type":"select","options":["自然日光","室内灯光","清晨逆光","黄昏侧光"]},{"name":"feature","label":"突出特点","type":"select","options":["材质科技","人体工学","便携设计","防水性能"]}]', 'image', 'dumbbell', 72, 1, 2, 35, 1),

('TPL_MAIN_012', 'main_image', '宠物用品主图', '宠物食品、玩具、窝具等', '{{product_name}}宠物产品主图。{{pet_type}}使用场景，{{bg}}背景，展示{{feature}}，画面{{mood}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"pet_type","label":"适用宠物","type":"select","options":["猫","狗","小型宠物","水族"]},{"name":"bg","label":"背景","type":"select","options":["家庭场景","户外草地","纯色背景","宠物使用实景"]},{"name":"feature","label":"突出特点","type":"select","options":["天然成分","耐用设计","趣味互动","舒适材质"]},{"name":"mood","label":"画面氛围","type":"select","options":["活泼欢乐","温馨治愈","高端专业","自然清新"]}]', 'image', 'paw', 70, 1, 2, 28, 1),

('TPL_MAIN_013', 'main_image', '汽车用品主图', '车载配件、养护产品等', '{{product_name}}汽车用品主图。{{bg}}背景，{{angle}}角度，展示{{feature}}，体现{{style}}风格。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["车内实景","纯黑科技","车库场景","户外公路"]},{"name":"angle","label":"角度","type":"select","options":["产品特写","安装效果","使用场景","对比展示"]},{"name":"feature","label":"突出特点","type":"select","options":["材质质感","安装便捷","科技功能","安全防护"]},{"name":"style","label":"风格","type":"select","options":["极简科技","硬核专业","高端奢华","实用主义"]}]', 'image', 'car', 68, 1, 2, 22, 1),

('TPL_MAIN_014', 'main_image', '图书文具主图', '书籍、文具、办公用品等', '{{product_name}}主图。{{layout}}构图，{{bg}}背景，{{prop}}搭配，{{light}}光线，体现{{style}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"layout","label":"构图","type":"select","options":["平铺俯拍","45度陈列","手持展示","场景融入"]},{"name":"bg","label":"背景","type":"select","options":["纯白","木质桌面","大理石","织物纹理"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：咖啡杯、绿植"},{"name":"light","label":"光线","type":"select","options":["窗边自然光","暖色台灯","柔光箱","侧逆光"]},{"name":"style","label":"风格","type":"select","options":["文艺清新","极简商务","复古质感","日系治愈"]}]', 'image', 'book', 66, 1, 2, 19, 1),

('TPL_MAIN_015', 'main_image', '节庆礼品主图', '节日礼品、礼盒、贺卡等', '{{product_name}}节庆礼品主图。{{holiday}}主题，{{color_scheme}}配色，{{decoration}}装饰元素，{{mood}}氛围。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"holiday","label":"节日","type":"select","options":["春节","情人节","母亲节","中秋节","圣诞节","元旦"]},{"name":"color_scheme","label":"配色方案","type":"select","options":["中国红+金","粉色+白","暖橙+棕","深蓝+银","绿+红"]},{"name":"decoration","label":"装饰元素","type":"text","required":false,"placeholder":"如：丝带、灯串、花瓣"},{"name":"mood","label":"氛围","type":"select","options":["喜庆热闹","浪漫温馨","感恩暖心","团圆美满"]}]', 'image', 'gift', 64, 1, 2, 31, 1),

-- main_image 16-20
('TPL_MAIN_016', 'main_image', '医疗器械主图', '血压计、按摩仪、护具等', '{{product_name}}医疗器械主图。{{bg}}背景，{{display}}展示方式，突出{{feature}}，标注{{cert}}认证。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["纯白医疗","浅蓝科技","暖灰专业"]},{"name":"display","label":"展示方式","type":"select","options":["产品居中","使用演示","包装+产品","细节特写"]},{"name":"feature","label":"突出特点","type":"select","options":["精准测量","智能互联","便携设计","舒适佩戴"]},{"name":"cert","label":"认证标识","type":"select","options":["CE/FDA角标","医疗器械注册号","检测报告图标"]}]', 'image', 'heart', 62, 1, 2, 15, 1),

('TPL_MAIN_017', 'main_image', '灯具照明主图', '台灯、吊灯、氛围灯等', '{{product_name}}照明产品主图。{{scene}}场景，{{light_temp}}色温效果，{{angle}}角度，展示{{feature}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"scene","label":"场景","type":"select","options":["书房阅读","卧室温馨","客厅主灯","户外庭院"]},{"name":"light_temp","label":"色温效果","type":"select","options":["暖黄2700K","自然4000K","冷白6000K"]},{"name":"angle","label":"角度","type":"select","options":["灯具特写","光效氛围","安装效果","开关对比"]},{"name":"feature","label":"突出特点","type":"select","options":["护眼无频闪","智能调光","极简设计","高显色指数"]}]', 'image', 'lightbulb', 60, 1, 2, 17, 1),

('TPL_MAIN_018', 'main_image', '工具五金主图', '手工具、电动工具、五金配件等', '{{product_name}}工具产品主图。{{bg}}背景，{{display}}展示，突出{{feature}}，体现{{texture}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["纯黑工业","工作台场景","白底简洁"]},{"name":"display","label":"展示方式","type":"select","options":["产品特写","握持演示","套装陈列","爆炸图"]},{"name":"feature","label":"突出特点","type":"select","options":["材质耐用","人体工学","精密工艺","多功能"]},{"name":"texture","label":"质感","type":"select","options":["金属拉丝","磨砂橡胶","镜面抛光","碳纤维纹"]}]', 'image', 'tool', 58, 1, 2, 12, 1),

('TPL_MAIN_019', 'main_image', '园艺花卉主图', '盆栽、花盆、园艺工具等', '{{product_name}}园艺产品主图。{{bg}}背景，{{season}}季节氛围，{{prop}}搭配，体现{{style}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["花园实景","纯白","木质阳台","温室"]},{"name":"season","label":"季节氛围","type":"select","options":["春花烂漫","夏日绿荫","秋叶暖阳","冬日温室"]},{"name":"prop","label":"搭配","type":"text","required":false,"placeholder":"如：洒水壶、木架"},{"name":"style","label":"风格","type":"select","options":["自然田园","日式禅意","现代简约","欧式古典"]}]', 'image', 'flower', 56, 1, 2, 10, 1),

('TPL_MAIN_020', 'main_image', '跨境通用主图', '适合Amazon/Shopee/Lazada等跨境平台', '为{{product_name}}生成跨境平台主图。纯白背景(RGB 255,255,255)，{{product_name}}占据画面{{ratio}}，{{angle}}角度，突出{{feature}}，符合{{platform}}平台要求。', '[{"name":"product_name","label":"产品名称(英文)","type":"text","required":true,"placeholder":"如：Wireless Earbuds"},{"name":"ratio","label":"商品占比","type":"select","options":["85%","90%","95%"]},{"name":"angle","label":"角度","type":"select","options":["正面","45度","侧视","多角度拼接"]},{"name":"feature","label":"突出卖点","type":"text","required":true,"placeholder":"如：Active Noise Cancelling"},{"name":"platform","label":"目标平台","type":"select","options":["Amazon","Shopee","Lazada","eBay","AliExpress"]}]', 'image', 'globe', 99, 1, 2, 55, 1);

-- ==================== 2. scene 场景图模板 (15个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_SCENE_001', 'scene', '家居生活场景', '服装/家居品的客厅/卧室场景图', '{{product_name}}摆放在{{room}}中。{{style}}风格装修，{{time}}自然光从{{window_direction}}洒入，{{product_name}}{{placement}}摆放，画面{{mood}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"room","label":"房间","type":"select","options":["客厅","卧室","书房","阳台","玄关"]},{"name":"style","label":"风格","type":"select","options":["北欧简约","日式原木","现代轻奢","美式复古"]},{"name":"time","label":"时段","type":"select","options":["清晨","午后","黄昏","夜晚暖灯"]},{"name":"window_direction","label":"窗向","type":"select","options":["左侧","右侧","正面","顶部天窗"]},{"name":"placement","label":"摆放方式","type":"select","options":["桌面陈列","沙发搭配","地面摆放","墙面悬挂"]},{"name":"mood","label":"氛围","type":"select","options":["温馨舒适","高级精致","自然清新","慵懒随性"]}]', 'image', 'home', 98, 1, 2, 89, 1),

('TPL_SCENE_002', 'scene', '户外自然场景', '户外/自然光线下的产品展示', '{{product_name}}放置于{{outdoor_scene}}。{{weather}}天气，{{time_of_day}}光线，{{product_name}}{{usage}}使用/展示中，{{composition}}构图。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"outdoor_scene","label":"户外场景","type":"select","options":["公园草地","海滩","森林小径","城市街头","花园","山间溪流"]},{"name":"weather","label":"天气","type":"select","options":["晴天","多云柔光","雨后清新","雾天朦胧"]},{"name":"time_of_day","label":"时间","type":"select","options":["黄金时刻","正午","阴天漫射","蓝色时刻"]},{"name":"usage","label":"产品状态","type":"select","options":["静态陈列","手持使用","穿戴展示","场景融入"]},{"name":"composition","label":"构图","type":"select","options":["三分法","中心对称","引导线","框架构图"]}]', 'image', 'sun', 96, 1, 2, 76, 1),

('TPL_SCENE_003', 'scene', '工作室影棚场景', '专业影棚布光产品场景图', '{{product_name}}专业棚拍场景。{{bg_type}}背景，{{light_setup}}布光方案，{{product_name}}{{angle}}角度，{{prop}}专业搭配，突出{{highlight}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg_type","label":"背景","type":"select","options":["无缝白","渐变灰","彩色背景纸","纹理背景"]},{"name":"light_setup","label":"布光方案","type":"select","options":["三点布光","环形布光","侧逆光","蝴蝶光"]},{"name":"angle","label":"拍摄角度","type":"select","options":["正面","45度","俯拍","仰拍","微距"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：亚克力台、干冰"},{"name":"highlight","label":"突出点","type":"select","options":["整体质感","材质细节","光影层次","色彩还原"]}]', 'image', 'camera', 94, 1, 2, 63, 1),

('TPL_SCENE_004', 'scene', '咖啡厅/商业空间场景', '餐饮器具、文创产品的生活场景', '{{product_name}}置于{{space}}中。暖色灯光，{{table_top}}桌面，{{product_name}}与{{companion}}搭配摆放，{{angle}}视角，氛围{{mood}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"space","label":"空间","type":"select","options":["咖啡厅角落","书店一角","精品店陈列","餐厅桌面"]},{"name":"table_top","label":"桌面材质","type":"select","options":["木质纹理","大理石","水泥灰","复古瓷砖"]},{"name":"companion","label":"搭配物品","type":"text","required":false,"placeholder":"如：咖啡杯、杂志、绿植"},{"name":"angle","label":"视角","type":"select","options":["俯拍","45度","水平","近距离"]},{"name":"mood","label":"氛围","type":"select","options":["慵懒午后","精致生活","文艺复古","温暖治愈"]}]', 'image', 'coffee', 92, 1, 2, 58, 1),

('TPL_SCENE_005', 'scene', '季节主题场景', '春夏秋冬四季氛围产品图', '{{product_name}}{{season}}主题场景。{{season_element}}季节元素，{{color_tone}}色调，{{product_name}}{{placement}}其中，{{light_quality}}光线质感。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"season","label":"季节","type":"select","options":["春","夏","秋","冬"]},{"name":"season_element","label":"季节元素","type":"text","required":false,"placeholder":"如：樱花、落叶、雪花"},{"name":"color_tone","label":"色调","type":"select","options":["樱花粉+薄荷绿(春)","天空蓝+向日葵黄(夏)","枫叶橙+大地棕(秋)","冰雪蓝+暖白(冬)"]},{"name":"placement","label":"摆放","type":"select","options":["融入场景","前景特写","中景展示","背景点缀"]},{"name":"light_quality","label":"光线质感","type":"select","options":["柔光","逆光剪影","斑驳光影","清冷散射"]}]', 'image', 'cloud', 90, 1, 2, 52, 1),

('TPL_SCENE_006', 'scene', '节日主题场景', '春节/圣诞/情人节等节日氛围', '{{product_name}}{{festival}}主题场景。主色调{{color_scheme}}，{{deco}}节日装饰，{{atmosphere}}氛围，{{product_name}}作为{{role}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"festival","label":"节日","type":"select","options":["春节","圣诞节","情人节","万圣节","感恩节","新年"]},{"name":"color_scheme","label":"配色","type":"select","options":["红+金","绿+红+白","粉+红","橙+黑","棕+橙","金+银"]},{"name":"deco","label":"装饰元素","type":"text","required":false,"placeholder":"如：灯笼、彩灯、玫瑰花瓣"},{"name":"atmosphere","label":"氛围","type":"select","options":["喜庆热闹","浪漫温馨","搞怪趣味","温馨感恩"]},{"name":"role","label":"产品角色","type":"select","options":["节日主角","礼盒搭配","装饰元素","场景焦点"]}]', 'image', 'gift', 88, 1, 2, 48, 1),

('TPL_SCENE_007', 'scene', '极简白底场景', '纯白/极简背景，突出产品本身', '{{product_name}}极简白底场景。纯白背景，{{shadow_style}}阴影，{{product_name}}{{angle}}展示，{{accent}}点缀，画面干净{{feel}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"shadow_style","label":"阴影风格","type":"select","options":["自然投影","悬浮阴影","无阴影","柔和倒影"]},{"name":"angle","label":"展示角度","type":"select","options":["正面居中","45度悬浮","多角度组合","细节展开"]},{"name":"accent","label":"点缀","type":"select","options":["无点缀","微量植物","几何道具","光影分割"]},{"name":"feel","label":"视觉感受","type":"select","options":["纯净","高级","呼吸感","留白意境"]}]', 'image', 'square', 86, 1, 2, 71, 1),

('TPL_SCENE_008', 'scene', '模特上身场景', '服装/配饰的上身实拍效果', '{{model_desc}}模特穿着{{product_name}}，{{pose}}姿势，{{location}}场景，{{light}}光线，展示{{show}}效果，{{style}}风格。', '[{"name":"model_desc","label":"模特描述","type":"text","required":true,"placeholder":"如：亚洲女性、长发、身高165"},{"name":"product_name","label":"服装名称","type":"text","required":true},{"name":"pose","label":"姿势","type":"select","options":["自然行走","正面站立","侧身回眸","坐姿","动态转身"]},{"name":"location","label":"场景","type":"select","options":["城市街头","室内空间","自然户外","纯色背景"]},{"name":"light","label":"光线","type":"select","options":["自然日光","柔光","逆光","闪光灯"]},{"name":"show","label":"展示重点","type":"select","options":["整体版型","面料垂感","细节设计","搭配效果"]},{"name":"style","label":"风格","type":"select","options":["时尚街拍","韩系温柔","日系清新","欧美大气","文艺复古"]}]', 'image', 'user', 84, 1, 2, 95, 1),

('TPL_SCENE_009', 'scene', '悬浮/创意场景', '产品悬浮、动态、艺术化展示', '{{product_name}}创意悬浮场景。{{bg}}背景，{{product_name}}悬浮于{{position}}位置，{{dynamic_element}}动态元素环绕，{{light_effect}}光效，{{style}}风格。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["深色渐变","霓虹暗色","纯白","星空","色彩爆炸"]},{"name":"position","label":"悬浮位置","type":"select","options":["画面中心","对角线","螺旋排列","爆炸散开"]},{"name":"dynamic_element","label":"动态元素","type":"text","required":false,"placeholder":"如：水花、花瓣、光粒子"},{"name":"light_effect","label":"光效","type":"select","options":["霓虹灯管","激光线条","粒子散射","镜面反射","丁达尔光"]},{"name":"style","label":"风格","type":"select","options":["赛博朋克","极简未来","梦幻仙境","潮流街头","奢华水晶"]}]', 'image', 'sparkles', 82, 1, 2, 67, 1),

('TPL_SCENE_010', 'scene', '美食摆拍场景', '食品饮料的专业美食摄影', '{{product_name}}美食摆拍。{{table}}桌面，{{prop}}道具搭配，{{angle}}角度，{{light}}光线，{{product_name}}呈现{{texture}}质感，{{style}}风格。', '[{"name":"product_name","label":"食品名称","type":"text","required":true},{"name":"table","label":"桌面","type":"select","options":["原木餐桌","大理石台面","复古瓷砖","纯色背景纸"]},{"name":"prop","label":"搭配道具","type":"text","required":false,"placeholder":"如：刀叉、餐巾、鲜花"},{"name":"angle","label":"拍摄角度","type":"select","options":["45度斜拍","俯拍","水平","微距"]},{"name":"light","label":"光线","type":"select","options":["窗边自然光","侧逆光","柔光箱","暖色氛围光"]},{"name":"texture","label":"食物质感","type":"select","options":["酥脆金黄","水润光泽","绵软细腻","浓郁拉丝"]},{"name":"style","label":"风格","type":"select","options":["高级餐厅","日系治愈","家庭温馨","极简精致"]}]', 'image', 'utensils', 80, 1, 2, 73, 1),

('TPL_SCENE_011', 'scene', '科技感场景', '3C/数码产品的科技场景展示', '{{product_name}}科技场景。{{bg}}背景，{{light_effect}}灯光，{{product_name}}{{display_mode}}，{{accents}}科技元素点缀，体现{{feel}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"bg","label":"背景","type":"select","options":["深黑科技","暗蓝渐变","霓虹暗色","金属网格"]},{"name":"light_effect","label":"灯光效果","type":"select","options":["霓虹灯管","电路板光纹","粒子流动","激光扫描线"]},{"name":"display_mode","label":"展示方式","type":"select","options":["悬浮","爆炸分解","透视内部","动态使用"]},{"name":"accents","label":"科技元素","type":"text","required":false,"placeholder":"如：数据流、光晕、电路纹理"},{"name":"feel","label":"视觉感受","type":"select","options":["赛博朋克","未来极简","硬核工业","数字艺术"]}]', 'image', 'cpu', 78, 1, 2, 45, 1),

('TPL_SCENE_012', 'scene', '水花/液体场景', '饮品、美妆等液体的动态场景', '{{product_name}}水花场景。{{liquid_type}}液体，{{splash_style}}飞溅形态，{{bg}}背景，{{light}}光线穿过液体，{{product_name}}{{position}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"liquid_type","label":"液体类型","type":"select","options":["清水","橙色果汁","牛奶","金色香槟","深色咖啡"]},{"name":"splash_style","label":"飞溅形态","type":"select","options":["皇冠水花","环绕飞溅","滴落效果","涌动波浪","静态镜面"]},{"name":"bg","label":"背景","type":"select","options":["纯黑","纯白","渐变蓝","暖色逆光"]},{"name":"light","label":"光线","type":"select","options":["侧逆光透射","高速闪光","柔光漫反射","水下折射"]},{"name":"position","label":"产品位置","type":"select","options":["水中悬浮","水花之上","水花包围","水面静置"]}]', 'image', 'droplet', 76, 1, 2, 39, 1),

('TPL_SCENE_013', 'scene', '平铺/俯拍场景', '服装/饰品/文具的平铺俯拍', '{{product_name}}俯拍平铺。{{surface}}台面，{{layout}}摆放布局，{{prop}}搭配物品，{{light}}光线，整体{{style}}风格。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"surface","label":"台面","type":"select","options":["原木地板","白色桌面","大理石","水泥灰","布料纹理"]},{"name":"layout","label":"布局","type":"select","options":["整齐排列","随意散落","套装组合","色彩渐变"]},{"name":"prop","label":"搭配物品","type":"text","required":false,"placeholder":"如：干花、杂志、眼镜"},{"name":"light","label":"光线","type":"select","options":["均匀柔光","窗影斑驳","侧光立体","硬光锐利"]},{"name":"style","label":"风格","type":"select","options":["极简","文艺","时尚编辑","学院风"]}]', 'image', 'grid', 74, 1, 2, 36, 1),

('TPL_SCENE_014', 'scene', '镜面/反射场景', '利用镜面/水面反射的高级展示', '{{product_name}}镜面场景。{{reflect_surface}}反射面，{{product_name}}置于{{position}}，{{light}}光线，反射出{{reflect_effect}}，营造{{feel}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"reflect_surface","label":"反射面","type":"select","options":["黑色镜面","水面","大理石抛光","金属板","玻璃"]},{"name":"position","label":"产品位置","type":"select","options":["镜面正中","边缘探出","悬浮反射","局部镜面"]},{"name":"light","label":"光线","type":"select","options":["侧逆光","顶光","柔光漫反射","彩色灯光"]},{"name":"reflect_effect","label":"反射效果","type":"select","options":["清晰倒影","模糊倒影","扭曲艺术","多重反射"]},{"name":"feel","label":"视觉感受","type":"select","options":["高端奢华","极简高级","梦幻艺术","未来科技"]}]', 'image', 'mirror', 72, 1, 2, 28, 1),

('TPL_SCENE_015', 'scene', '电商平台场景适配', '针对各平台主图场景规范的场景图', '{{product_name}}{{platform}}场景适配。{{bg_type}}背景，场景{{scene_type}}，{{product_name}}占比{{ratio}}，符合{{platform}}图片规范，色调{{color_tone}}。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"platform","label":"平台","type":"select","options":["淘宝/天猫","拼多多","京东","抖音电商","Amazon","Shopee"]},{"name":"bg_type","label":"背景","type":"select","options":["纯白","浅灰","场景","渐变色"]},{"name":"scene_type","label":"场景类型","type":"select","options":["生活场景","专业影棚","户外自然","创意氛围"]},{"name":"ratio","label":"产品占比","type":"select","options":["70%","80%","90%"]},{"name":"color_tone","label":"色调","type":"select","options":["暖色调","冷色调","中性色","平台推荐色"]}]', 'image', 'monitor', 70, 1, 2, 42, 1);

-- ==================== 3. video 视频模板 (10个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_VIDEO_001', 'video', '产品展示短视频', '15秒产品展示视频分镜脚本', '产品展示短视频(15秒)：\n镜头1(0-3s): {{product_name}}特写旋转，{{light_effect}}光效\n镜头2(3-8s): 场景中使用，{{scene}}环境\n镜头3(8-12s): 细节放大，突出{{feature}}\n镜头4(12-15s): 品牌logo+{{cta}}引导', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"light_effect","label":"光效","type":"select","options":["柔和自然光","霓虹闪烁","金色粒子","镜面反射"]},{"name":"scene","label":"使用场景","type":"select","options":["现代客厅","都市户外","工作室","咖啡馆"]},{"name":"feature","label":"核心卖点","type":"text","required":true,"placeholder":"如：防水性能"},{"name":"cta","label":"行动号召","type":"select","options":["立即购买","了解更多","限时优惠","新品首发"]}]', 'video', 'video', 98, 1, 2, 62, 1),

('TPL_VIDEO_002', 'video', '开箱体验视频', '产品开箱/拆封短视频脚本', '{{product_name}}开箱视频(20秒)：\n镜头1(0-4s): 包装盒外观，{{unbox_style}}开箱方式\n镜头2(4-10s): 产品取出过程，特写{{detail}}\n镜头3(10-16s): 产品全貌展示，{{light}}光线\n镜头4(16-20s): 首用体验，{{reaction}}反应+字幕', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"unbox_style","label":"开箱方式","type":"select","options":["刀划开封","撕拉条","掀盖","解绳"]},{"name":"detail","label":"开箱细节","type":"select","options":["包装质感","配件陈列","产品初露","保护膜撕下"]},{"name":"light","label":"光线","type":"select","options":["自然窗光","环形灯","暖色台灯","顶光"]},{"name":"reaction","label":"体验反应","type":"select","options":["惊喜","满足","专业评述","对比旧款"]}]', 'video', 'box', 95, 1, 2, 48, 1),

('TPL_VIDEO_003', 'video', '对比测评视频', '产品对比/评测视频分镜', '{{product_name}}对比测评(30秒)：\n镜头1(0-5s): 产品A vs 产品B并排\n镜头2(5-12s): {{dimension}}维度实测对比\n镜头3(12-22s): {{product_name}}优势特写，{{proof}}证明\n镜头4(22-30s): 结论+价格对比+购买建议', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"dimension","label":"对比维度","type":"select","options":["材质手感","性能速度","续航时间","外观设计","价格"]},{"name":"proof","label":"证明方式","type":"select","options":["数据图表","实测画面","放大对比","计时展示"]}]', 'video', 'bar-chart', 92, 1, 2, 35, 1),

('TPL_VIDEO_004', 'video', '教程使用视频', '产品使用教程/技巧短视频', '{{product_name}}使用教程(45秒)：\n镜头1(0-5s): 痛点引入，{{pain_point}}\n镜头2(5-15s): Step1 {{step1}}\n镜头3(15-25s): Step2 {{step2}}\n镜头4(25-35s): Step3 {{step3}}\n镜头5(35-45s): 效果展示+总结', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"pain_point","label":"痛点","type":"text","required":true,"placeholder":"如：每次化妆都卡粉"},{"name":"step1","label":"步骤1","type":"text","required":true},{"name":"step2","label":"步骤2","type":"text","required":true},{"name":"step3","label":"步骤3","type":"text","required":true}]', 'video', 'play-circle', 90, 1, 2, 55, 1),

('TPL_VIDEO_005', 'video', '生活场景Vlog', '产品融入日常Vlog视频', '{{product_name}}日常生活Vlog(30秒)：\n镜头1(0-4s): {{time}}起床/开始，环境空镜\n镜头2(4-12s): 使用{{product_name}}的过程，{{action}}\n镜头3(12-20s): 产品带来的改变，{{benefit}}\n镜头4(20-26s): 生活美好瞬间\n镜头5(26-30s): 产品特写+文字推荐', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"time","label":"时间段","type":"select","options":["清晨","午后","傍晚","周末"]},{"name":"action","label":"使用动作","type":"text","required":true,"placeholder":"如：冲一杯手冲咖啡"},{"name":"benefit","label":"产品带来的好处","type":"text","required":true,"placeholder":"如：3分钟搞定早餐"}]', 'video', 'film', 88, 1, 2, 72, 1),

('TPL_VIDEO_006', 'video', '转场创意视频', '多种转场特效的产品展示', '{{product_name}}创意转场视频(15秒)：\n镜头1(0-3s): {{product_name}}特写，{{trans1}}转场→\n镜头2(3-7s): 使用场景，{{trans2}}转场→\n镜头3(7-11s): 色彩切换({{color_change}})，{{trans3}}转场→\n镜头4(11-15s): 最终定格+品牌', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"trans1","label":"转场1","type":"select","options":["遮罩擦除","缩放跳切","旋转翻转","匹配形状"]},{"name":"trans2","label":"转场2","type":"select","options":["滑动","溶解","光晕过渡","色彩渐变"]},{"name":"trans3","label":"转场3","type":"select","options":["弹跳","遮罩","闪白","模糊"]},{"name":"color_change","label":"色彩切换","type":"select","options":["黑白→彩色","暖色→冷色","单色→多彩","复古→现代"]}]', 'video', 'sparkles', 86, 1, 2, 41, 1),

('TPL_VIDEO_007', 'video', '慢动作特写视频', '慢镜头产品细节展示', '{{product_name}}慢动作特写(15秒)：\n镜头1(0-5s): {{motion}}慢动作(120fps)，{{product_name}}{{action}}\n镜头2(5-10s): {{detail}}微距放大\n镜头3(10-15s): 恢复常速，产品完整展示+字幕', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"motion","label":"动作","type":"select","options":["水滴溅落","面料飘动","齿轮转动","液体倾泻","粉末飞扬","光线扫过"]},{"name":"action","label":"产品动作","type":"text","required":true,"placeholder":"如：缓缓旋转"},{"name":"detail","label":"细节","type":"select","options":["材质纹理","光泽变化","结构层次","色彩过渡"]}]', 'video', 'slow', 84, 1, 2, 33, 1),

('TPL_VIDEO_008', 'video', '文字动画视频', '文字动效+产品展示的营销视频', '{{product_name}}文字动画视频(20秒)：\n镜头1(0-4s): 标题文字弹出\"{{headline}}\"\n镜头2(4-10s): {{product_name}}产品镜头\n镜头3(10-14s): 卖点文字滚动\"{{bullet1}} | {{bullet2}} | {{bullet3}}\"\n镜头4(14-20s): CTA+品牌', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"headline","label":"标题文案","type":"text","required":true,"placeholder":"如：这个夏天，不一样的清凉"},{"name":"bullet1","label":"卖点1","type":"text","required":true},{"name":"bullet2","label":"卖点2","type":"text","required":true},{"name":"bullet3","label":"卖点3","type":"text","required":true}]', 'video', 'type', 82, 1, 2, 38, 1),

('TPL_VIDEO_009', 'video', 'ASMR质感视频', 'ASMR风格产品质感展示', '{{product_name}}ASMR质感视频(25秒)：\n镜头1(0-6s): 静音环境，{{product_name}}{{touch_action}}声音\n镜头2(6-13s): {{use_action}}过程，放大{{sound}}声音\n镜头3(13-19s): 细节质感，{{texture}}特写\n镜头4(19-25s): 渐弱音效，产品静置收尾', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"touch_action","label":"触碰动作","type":"select","options":["手指轻触","指甲刮过","翻开","按压"]},{"name":"use_action","label":"使用动作","type":"text","required":true,"placeholder":"如：倒入液体"},{"name":"sound","label":"重点声音","type":"select","options":["液体声","摩擦声","点击声","撕开声"]},{"name":"texture","label":"质感","type":"select","options":["磨砂表面","光滑镜面","柔软织物","金属光泽"]}]', 'video', 'headphones', 80, 1, 2, 26, 1),

('TPL_VIDEO_010', 'video', '平台适配短视频', '针对抖音/小红书/TikTok的视频模板', '{{product_name}}{{platform}}短视频({{duration}}秒)：\n镜头1: {{hook}}钩子开头\n镜头2: 产品核心卖点{{feature}}展示\n镜头3: 使用效果{{result}}\n镜头4: {{cta_style}}转化引导\n适配{{platform}}{{ratio}}比例, BGM: {{bgm}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"platform","label":"平台","type":"select","options":["抖音","小红书","TikTok","快手","视频号"]},{"name":"duration","label":"时长(秒)","type":"select","options":["15","30","60","90"]},{"name":"hook","label":"钩子开头","type":"select","options":["疑问句","反转","数据冲击","痛点直击","效果前置"]},{"name":"feature","label":"核心卖点","type":"text","required":true},{"name":"result","label":"效果展示","type":"select","options":["前后对比","实测数据","使用过程","达人推荐"]},{"name":"cta_style","label":"转化引导","type":"select","options":["评论互动","点击购物车","关注账号","私信领取"]},{"name":"ratio","label":"画面比例","type":"select","options":["9:16竖屏","16:9横屏","1:1方形"]},{"name":"bgm","label":"背景音乐","type":"select","options":["热门流行","轻快节奏","舒缓治愈","强节奏感","纯音乐"]}]', 'video', 'smartphone', 99, 1, 2, 81, 1);

-- ==================== 4. script 脚本模板 (10个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_SCRIPT_001', 'script', '抖音带货脚本', '抖音直播间/短视频带货口播', '【抖音带货脚本 - {{product_name}}】\n\n🎯 开场钩子(3秒): {{hook}}\n📦 产品引入(10秒): 你是否有{{pain_point}}的困扰？今天这款{{product_name}}，{{core_sell}}\n✨ 卖点展开(20秒): \n  - {{bullet1}}\n  - {{bullet2}}\n  - {{bullet3}}\n💰 价格锚点(10秒): 平时{{original_price}}，今天{{price}}\n🔥 逼单(5秒): {{scarcity}}，赶紧下单！', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"hook","label":"开场钩子","type":"text","required":true,"placeholder":"如：你家的洗面奶可能白用了"},{"name":"pain_point","label":"痛点","type":"text","required":true},{"name":"core_sell","label":"一句话卖点","type":"text","required":true},{"name":"bullet1","label":"卖点1","type":"text","required":true},{"name":"bullet2","label":"卖点2","type":"text","required":true},{"name":"bullet3","label":"卖点3","type":"text","required":true},{"name":"original_price","label":"原价","type":"text","required":true},{"name":"price","label":"直播价","type":"text","required":true},{"name":"scarcity","label":"稀缺性","type":"select","options":["只剩100单","限时1小时","库存告急","手慢无","前50名赠品"]}]', 'text', 'shopping-cart', 98, 1, 2, 95, 1),

('TPL_SCRIPT_002', 'script', 'TikTok带货脚本', 'TikTok/海外短视频带货英文脚本', '【TikTok Script - {{product_name}}】\n\n🎬 Hook(0-3s): {{hook}}\n📱 Problem(3-8s): Struggling with {{pain_point}}? Meet {{product_name}}!\n✨ Features(8-20s):\n  - {{feature1}}\n  - {{feature2}}\n  - {{feature3}}\n📊 Social Proof(20-25s): Over {{sales}} sold!\n🛒 CTA(25-30s): {{cta}}', '[{"name":"product_name","label":"Product Name","type":"text","required":true,"placeholder":"e.g. Wireless Earbuds"},{"name":"hook","label":"Hook(English)","type":"text","required":true,"placeholder":"e.g. Stop wasting money on bad audio!"},{"name":"pain_point","label":"Pain Point","type":"text","required":true},{"name":"feature1","label":"Feature 1","type":"text","required":true},{"name":"feature2","label":"Feature 2","type":"text","required":true},{"name":"feature3","label":"Feature 3","type":"text","required":true},{"name":"sales","label":"Sales Number","type":"text","required":true,"placeholder":"e.g. 10,000"},{"name":"cta","label":"CTA","type":"select","options":["Link in bio!","Grab yours now!","Limited stock!","Click the link!"]}]', 'text', 'globe', 96, 1, 2, 62, 1),

('TPL_SCRIPT_003', 'script', '视频号口播脚本', '微信视频号/私域带货口播', '【视频号口播 - {{product_name}}】\n\n👋 亲切开场(5秒): 朋友们好，今天给大家分享一款{{product_name}}\n💡 真实体验(15秒): 我用了{{period}}，最大的感受是{{feeling}}\n📖 深度讲解(25秒): {{detail_desc}}\n🔗 私域转化(5秒): 想了解的朋友评论区扣1，我私信你', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"period","label":"使用时长","type":"text","required":true,"placeholder":"如：一个月"},{"name":"feeling","label":"使用感受","type":"text","required":true,"placeholder":"如：皮肤真的变好了"},{"name":"detail_desc","label":"深度讲解","type":"text","required":true,"placeholder":"详细介绍成分/材质/使用方式"}]', 'text', 'wechat', 94, 1, 2, 43, 1),

('TPL_SCRIPT_004', 'script', '快手带货脚本', '快手老铁风格带货口播', '【快手带货 - {{product_name}}】\n\n🎯 老铁开场(3秒): 老铁们！今天这{{product_name}}太{{adj}}了！\n💪 真实验证(12秒): 咱不整虚的，直接{{test_action}}给你看\n📢 核心卖点(15秒): {{core_point}}\n💰 源头价(5秒): 源头工厂直发，{{price}}包邮到家！\n🔔 关注引导(3秒): 点亮红心加关注，每天好货不重样！', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"adj","label":"形容词","type":"text","required":true,"placeholder":"如：牛、香、绝"},{"name":"test_action","label":"验证动作","type":"text","required":true,"placeholder":"如：拿锤子砸、火烧、水冲"},{"name":"core_point","label":"核心卖点","type":"text","required":true},{"name":"price","label":"价格","type":"text","required":true}]', 'text', 'zap', 92, 1, 2, 38, 1),

('TPL_SCRIPT_005', 'script', '小红书视频脚本', '小红书种草视频口播脚本', '【小红书视频 - {{product_name}}】\n\n🌸 温柔开场(3秒): 哈喽姐妹们～今天来分享{{product_name}}\n✨ 亮点预告(5秒): 这个{{highlight}}真的绝了！\n📸 实物展示(15秒): {{show_desc}}\n💄 上脸/上身效果(10秒): {{effect_desc}}\n🛍 购入信息(5秒): {{buy_info}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"highlight","label":"亮点","type":"text","required":true,"placeholder":"如：颜色、质地、效果"},{"name":"show_desc","label":"实物展示描述","type":"text","required":true},{"name":"effect_desc","label":"上手/上身效果","type":"text","required":true},{"name":"buy_info","label":"购入信息","type":"text","required":true,"placeholder":"如：🍑XX旗舰店、XX直播间"}]', 'text', 'heart', 90, 1, 2, 56, 1),

('TPL_SCRIPT_006', 'script', 'B站/长视频脚本', 'B站/YouTube长视频详细评测脚本', '【长视频评测 - {{product_name}}】\n\n📋 开场(15秒): 今天深度评测{{product_name}}，从{{dimensions}}个维度实测\n📐 开箱(2分钟): 包装、配件、第一印象\n🔬 实测(4分钟): {{test_items}}\n📊 数据总结(1分钟): 跑分/数据\n👍 优缺点总结(30秒): 适合/不适合人群\n🔔 结尾互动: 点赞投币收藏三连～', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"dimensions","label":"评测维度数量","type":"select","options":["5","7","10"]},{"name":"test_items","label":"实测项目(分条)","type":"text","required":true,"placeholder":"如：1.屏幕色域测试 2.续航实测 3.游戏帧率"}]', 'text', 'youtube', 88, 1, 2, 29, 1),

('TPL_SCRIPT_007', 'script', '直播带货全场脚本', '完整直播带货流程脚本(2小时)', '【直播脚本 - {{product_name}} 专场】\n\n⏰ 预热(5分钟): {{warm_up}}\n📦 第一款(20分钟): {{product1}} - 福利款引流\n💰 第二款(25分钟): {{product2}} - 利润款主推\n🎁 第三款(15分钟): {{product3}} - 赠品战术\n🔄 循环(45分钟): 以上3款轮播+逼单\n🔚 收尾(10分钟): 预告下一场', '[{"name":"warm_up","label":"预热内容","type":"text","required":true,"placeholder":"如：发红包、抽奖预告"},{"name":"product1","label":"福利款","type":"text","required":true},{"name":"product2","label":"主推利润款","type":"text","required":true},{"name":"product3","label":"赠品策略","type":"text","required":true}]', 'text', 'radio', 86, 1, 2, 22, 1),

('TPL_SCRIPT_008', 'script', '剧情带货脚本', '剧情/情景短剧带货脚本', '【剧情带货 - {{product_name}}】\n\n📺 场景: {{scene_setting}}\n👤 角色: {{characters}}\n📝 剧情(45秒):\n  开头(10s): {{conflict}} 矛盾/问题出现\n  转折(15s): {{product_name}}出现解决问题\n  高潮(10s): 问题解决，{{result}}\n  收尾(10s): 产品特写+转化引导', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"scene_setting","label":"场景设定","type":"text","required":true,"placeholder":"如：办公室、家庭客厅、约会餐厅"},{"name":"characters","label":"角色设定","type":"text","required":true,"placeholder":"如：同事A(烦恼中)、同事B(推荐产品)"},{"name":"conflict","label":"矛盾/问题","type":"text","required":true,"placeholder":"如：衣服弄脏了马上面试"},{"name":"result","label":"结果","type":"text","required":true}]', 'text', 'film', 84, 1, 2, 47, 1),

('TPL_SCRIPT_009', 'script', '知识科普脚本', '产品知识/行业科普类短视频脚本', '【知识科普 - {{product_name}}】\n\n🧠 冷知识/误区(3秒): {{hook_fact}}\n🔍 原理解析(15秒): {{explanation}}\n📊 数据支撑(8秒): {{data_point}}\n✅ 正确做法(8秒): {{solution}}，选{{product_name}}就对了\n📢 互动(3秒): 你踩过这个坑吗？评论区见', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"hook_fact","label":"开场冷知识/误区","type":"text","required":true,"placeholder":"如：90%的人洗脸方式都是错的"},{"name":"explanation","label":"原理/解析","type":"text","required":true},{"name":"data_point","label":"数据支撑","type":"text","required":true,"placeholder":"如：实验证明...、数据显示..."},{"name":"solution","label":"正确做法","type":"text","required":true}]', 'text', 'book-open', 82, 1, 2, 34, 1),

('TPL_SCRIPT_010', 'script', '节日/大促脚本', '节日/618/双11等大促带货脚本', '【{{campaign}}促销脚本 - {{product_name}}】\n\n🎊 节日氛围(3秒): {{festival_greeting}}\n💰 价格轰炸(10秒): 原价{{original}}，{{campaign}}到手只要{{price}}！\n🎁 赠品叠加(8秒): 买就送{{gift}}，前100名再加{{extra_gift}}\n⏰ 限时限量(8秒): {{deadline}}截止，库存仅剩{{stock}}件\n📲 行动指令(5秒): 点击下方购物车，现在就抢！', '[{"name":"campaign","label":"大促名称","type":"select","options":["618","双11","双12","年货节","38节","520","七夕","中秋节"]},{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"festival_greeting","label":"节日开场白","type":"text","required":true,"placeholder":"如：双11狂欢来了！"},{"name":"original","label":"原价","type":"text","required":true},{"name":"price","label":"大促价","type":"text","required":true},{"name":"gift","label":"赠品","type":"text","required":true},{"name":"extra_gift","label":"额外赠品","type":"text","required":true},{"name":"deadline","label":"截止时间","type":"text","required":true},{"name":"stock","label":"剩余库存","type":"text","required":true}]', 'text', 'tag', 99, 1, 2, 68, 1);

-- ==================== 5. copy 电商文案模板 (10个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_COPY_001', 'copy', '商品标题生成', '多平台商品标题+关键词优化', '为{{product_name}}生成{{platform}}商品标题：\n1. 品牌词: {{brand}}\n2. 核心词: {{product_name}}\n3. 属性词: {{attrs}}\n4. 场景词: {{scenes}}\n5. 促销词: {{promo}}\n组合格式: {{title_format}}\n优化方向: {{optimize_for}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"platform","label":"目标平台","type":"select","options":["淘宝","拼多多","京东","抖音","Amazon","Shopee","Lazada"]},{"name":"brand","label":"品牌名","type":"text","required":false,"placeholder":"如：小米"},{"name":"attrs","label":"属性词","type":"text","required":true,"placeholder":"如：纯棉 宽松 韩版 夏季"},{"name":"scenes","label":"场景词","type":"text","required":true,"placeholder":"如：通勤 约会 旅行"},{"name":"promo","label":"促销词","type":"text","required":false,"placeholder":"如：买一送一 第二件半价"},{"name":"title_format","label":"标题格式","type":"select","options":["品牌+核心词+属性词+场景词","促销词+核心词+属性词","核心词+长尾词+属性词","品牌+核心词+卖点词+场景词"]},{"name":"optimize_for","label":"优化方向","type":"select","options":["搜索SEO","点击率","转化率","平台推荐"]}]', 'text', 'file-text', 98, 1, 2, 105, 1),

('TPL_COPY_002', 'copy', '商品卖点文案', '详情页卖点/Bullet Point', '为{{product_name}}生成{{count}}条卖点文案：\n目标受众: {{audience}}\n核心卖点: {{selling_points}}\n文案风格: {{tone}}\n语言: {{language}}\n每条{{max_length}}字以内', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"count","label":"生成数量","type":"select","options":["3","5","7","10"]},{"name":"audience","label":"目标受众","type":"text","required":true,"placeholder":"如：25-35岁都市白领女性"},{"name":"selling_points","label":"核心卖点(逗号分隔)","type":"text","required":true,"placeholder":"如：深层补水,持久12小时,敏感肌可用"},{"name":"tone","label":"文案风格","type":"select","options":["专业权威","亲切口语","极简高端","年轻潮流","治愈温暖"]},{"name":"language","label":"语言","type":"select","options":["中文简体","中文繁体","英文","日文","韩文"]},{"name":"max_length","label":"每条字数上限","type":"select","options":["20","50","100","150"]}]', 'text', 'star', 96, 1, 2, 92, 1),

('TPL_COPY_003', 'copy', '详情页文案', '完整商品详情页内容', '为{{product_name}}生成完整详情页文案：\n\n📝 【产品参数】:\n- 品牌: {{brand}}\n- 规格: {{specs}}\n🔍 【核心卖点】:\n从{{selling_angles}}角度展开\n📸 【使用场景】:\n{{usage_scenes}}\n❓ 【Q&A】:\n针对{{faq_topics}}解答顾虑', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"brand","label":"品牌","type":"text","required":false},{"name":"specs","label":"规格参数","type":"text","required":true,"placeholder":"如：尺寸30x20cm 重量500g 材质纯棉"},{"name":"selling_angles","label":"卖点角度(逗号分隔)","type":"text","required":true,"placeholder":"如：材质,工艺,设计,使用体验"},{"name":"usage_scenes","label":"使用场景(逗号分隔)","type":"text","required":true,"placeholder":"如：居家日常,户外旅行,办公使用"},{"name":"faq_topics","label":"FAQ话题","type":"text","required":true,"placeholder":"如：清洗方式,尺寸选择,退换货"}]', 'text', 'layout', 94, 1, 2, 78, 1),

('TPL_COPY_004', 'copy', '促销活动文案', '限时折扣/满减/闪购文案', '{{promo_type}}活动文案 - {{product_name}}：\n\n🔥 活动主题: {{theme}}\n💰 优惠力度: {{discount_desc}}\n⏰ 时间限制: {{time_limit}}\n🎁 叠加福利: {{bonus}}\n📲 转化引导: {{cta}}', '[{"name":"promo_type","label":"促销类型","type":"select","options":["限时折扣","满减","闪购","秒杀","拼团","预售","买赠"]},{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"theme","label":"活动主题","type":"text","required":true,"placeholder":"如：夏日冰点价"},{"name":"discount_desc","label":"优惠描述","type":"text","required":true,"placeholder":"如：直降200元，到手仅299"},{"name":"time_limit","label":"时间限制","type":"text","required":true,"placeholder":"如：仅限7月20日 10:00-22:00"},{"name":"bonus","label":"叠加福利","type":"text","required":false,"placeholder":"如：前50名送赠品、满2件再减50"},{"name":"cta","label":"转化引导","type":"select","options":["立即抢购","限量秒杀","点击下单","先领券再下单","收藏加购"]}]', 'text', 'percent', 92, 1, 2, 86, 1),

('TPL_COPY_005', 'copy', '跨境英文Listing', 'Amazon/Shopee英文产品描述', 'Generate {{platform}} listing for {{product_name}}:\n\nTitle: Optimize for {{platform}} SEO\nBullet Points: {{count}} bullets, each {{words}} words\nDescription: {{tone}} style, {{paragraphs}} paragraphs\nKeywords(backend): Hidden search terms', '[{"name":"product_name","label":"Product Name","type":"text","required":true},{"name":"platform","label":"Platform","type":"select","options":["Amazon","Shopee","eBay","Walmart","AliExpress"]},{"name":"count","label":"Bullet Points","type":"select","options":["5","7","10"]},{"name":"words","label":"Words per bullet","type":"select","options":["30","50","100"]},{"name":"tone","label":"Tone","type":"select","options":["Professional","Friendly","Premium","Technical","Casual"]},{"name":"paragraphs","label":"Description paragraphs","type":"select","options":["2","3","4"]}]', 'text', 'globe', 99, 1, 2, 68, 1),

('TPL_COPY_006', 'copy', '主图标签文案', '主图上贴标/角标/水印文案', '为{{product_name}}生成{{count}}条主图标签文案：\n标签类型: {{label_type}}\n文案风格: {{tone}}\n语言: {{language}}\n每条{{max_chars}}字以内，醒目易读', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"count","label":"生成数量","type":"select","options":["5","10","15"]},{"name":"label_type","label":"标签类型","type":"select","options":["卖点标(如:防水/透气)","价格标(如:到手39元)","认证标(如:CE认证)","排名标(如:类目TOP1)","赠品标(如:买二送一)"]},{"name":"tone","label":"文案风格","type":"select","options":["简洁有力","夸张吸引","信任背书","温馨推荐"]},{"name":"language","label":"语言","type":"select","options":["中文","英文","中英双语"]},{"name":"max_chars","label":"每条字数上限","type":"select","options":["4","6","8","10"]}]', 'text', 'tag', 88, 1, 2, 56, 1),

('TPL_COPY_007', 'copy', '直播间贴片文案', '直播间贴片/公告/价格牌文案', '直播间{{scene}}场景贴片文案 - {{product_name}}：\n\n📌 产品名贴片: {{product_display_name}}\n💰 价格牌: {{price_display}}\n🎁 福利牌: {{benefit_display}}\n⏰ 倒计时牌: {{countdown_text}}', '[{"name":"scene","label":"贴片场景","type":"select","options":["产品讲解","价格公布","库存告急","福利秒杀","商品对比"]},{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"product_display_name","label":"产品名显示","type":"text","required":true,"placeholder":"如：XX精华液 · 30ml"},{"name":"price_display","label":"价格显示","type":"text","required":true,"placeholder":"如：到手价 ￥169"},{"name":"benefit_display","label":"福利显示","type":"text","required":true,"placeholder":"如：买2送1 | 顺丰包邮"},{"name":"countdown_text","label":"倒计时文案","type":"text","required":false,"placeholder":"如：最后3分钟 已抢836单"}]', 'text', 'tv', 86, 1, 2, 42, 1),

('TPL_COPY_008', 'copy', '评价回复模板', '买家评价回复/差评转化文案', '{{review_type}}评价回复 - {{product_name}}：\n\n买家评价: {{review_content}}\n回复策略: {{reply_strategy}}\n回复语气: {{tone}}\n回复目的: {{goal}}', '[{"name":"review_type","label":"评价类型","type":"select","options":["好评","中评","差评","追评","带图好评"]},{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"review_content","label":"买家评价内容","type":"text","required":true},{"name":"reply_strategy","label":"回复策略","type":"select","options":["感谢+引导追评","解释+补偿方案","道歉+退换货指引","认同+产品补充说明","热情+引导晒图"]},{"name":"tone","label":"回复语气","type":"select","options":["热情亲切","专业诚恳","幽默风趣","温馨贴心","正式礼貌"]},{"name":"goal","label":"回复目的","type":"select","options":["维护好评率","挽回差评用户","引导追评","提升转化","展示服务态度"]}]', 'text', 'message-circle', 84, 1, 2, 33, 1),

('TPL_COPY_009', 'copy', '推文/社群文案', '微信社群/朋友圈/公众号推送文案', '{{channel}}推文 - {{product_name}}：\n\n🎯 标题: {{title_style}}风格\n📝 正文: {{length}}长度，{{tone}}\n📸 配图建议: {{image_suggestion}}\n🔗 转化链路: {{link_flow}}', '[{"name":"channel","label":"渠道","type":"select","options":["微信社群","朋友圈","公众号","微博","小红书","知乎"]},{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"title_style","label":"标题风格","type":"select","options":["悬念式","数字式","痛点式","对比式","故事式"]},{"name":"length","label":"正文长度","type":"select","options":["短文案(100字)","中篇(300字)","长文(800字)","卖点清单(5-10条)"]},{"name":"tone","label":"语气","type":"select","options":["朋友推荐","专业科普","故事分享","性价比安利"]},{"name":"image_suggestion","label":"配图建议","type":"select","options":["产品实拍","场景使用","对比图","包装开箱","效果展示"]},{"name":"link_flow","label":"转化链路","type":"text","required":false,"placeholder":"如：点击小程序→新人券→立即下单"}]', 'text', 'share-2', 82, 1, 2, 47, 1),

('TPL_COPY_010', 'copy', '品牌故事文案', '品牌故事/创始人故事/品牌理念', '{{brand_name}}品牌故事：\n\n📖 故事角度: {{story_angle}}\n💡 核心理念: {{core_value}}\n👤 创始人: {{founder}}\n🏭 工艺/源头: {{craft_story}}\n❤️ 品牌温度: {{emotional_hook}}', '[{"name":"brand_name","label":"品牌名称","type":"text","required":true},{"name":"story_angle","label":"故事角度","type":"select","options":["创始人初心","源头工厂揭秘","用户真实故事","研发艰辛历程","传统工艺传承"]},{"name":"core_value","label":"核心理念","type":"text","required":true,"placeholder":"如：让每个人都能用上高品质好物"},{"name":"founder","label":"创始人/团队信息","type":"text","required":false,"placeholder":"如：10年行业经验"},{"name":"craft_story","label":"工艺/源头故事","type":"text","required":true,"placeholder":"如：30道工序、纯手工打磨"},{"name":"emotional_hook","label":"情感钩子","type":"text","required":true,"placeholder":"如：只为妈妈做一条好围巾"}]', 'text', 'bookmark', 80, 1, 2, 28, 1);

-- ==================== 6. viral-clone 种草文案模板 (10个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_VIRAL_001', 'viral-clone', '小红书种草文', '小红书风格图文笔记文案', '小红书种草 - {{product_name}}：\n\n📌 标题: {{title}}\n\n✨ 姐妹们！！我发现了{{emotion}}的{{product_name}}！！\n📝 正文:\n最近{{context}}，朋友推荐了这款{{product_name}}～\n用了一段时间，{{experience_desc}}\n💡 亮点: \n  - {{highlight1}}\n  - {{highlight2}}\n  - {{highlight3}}\n🏷 标签: {{tags}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"title","label":"标题","type":"text","required":true,"placeholder":"如：无限回购！这XX也太好用了叭"},{"name":"emotion","label":"惊喜程度","type":"select","options":["巨好用","绝绝子","太香了","相见恨晚","挖到宝了"]},{"name":"context","label":"入手背景","type":"text","required":true,"placeholder":"如：最近换季皮肤敏感"},{"name":"experience_desc","label":"使用感受","type":"text","required":true,"placeholder":"如：涂上瞬间吸收，第二天皮肤嫩到爆"},{"name":"highlight1","label":"亮点1","type":"text","required":true},{"name":"highlight2","label":"亮点2","type":"text","required":true},{"name":"highlight3","label":"亮点3","type":"text","required":true},{"name":"tags","label":"标签","type":"text","required":true,"placeholder":"如：#好物分享 #护肤 #空瓶记"}]', 'text', 'heart', 98, 1, 2, 113, 1),

('TPL_VIRAL_002', 'viral-clone', '小红书测评文', '小红书对比测评/横评文案', '小红书测评 - {{product_name}}：\n\n📌 标题: {{title}}\n\n🔬 测评对象: 市面{{count}}款{{category}}\n📊 测评维度: {{dimensions}}\n🏆 测评结果: {{product_name}}{{ranking}}\n💡 推荐理由:\n  {{reason1}}\n  {{reason2}}\n  {{reason3}}\n💬 总结: {{verdict}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"title","label":"标题","type":"text","required":true,"placeholder":"如：5款热门XX实测！最终留下的竟是它"},{"name":"count","label":"对比数量","type":"select","options":["3","5","8"]},{"name":"category","label":"品类","type":"text","required":true,"placeholder":"如：洗面奶、蓝牙耳机"},{"name":"dimensions","label":"测评维度(逗号分隔)","type":"text","required":true,"placeholder":"如：清洁力,温和度,性价比"},{"name":"ranking","label":"排名","type":"select","options":["第一名","红榜","强烈推荐","性价比之王"]},{"name":"reason1","label":"推荐理由1","type":"text","required":true},{"name":"reason2","label":"推荐理由2","type":"text","required":true},{"name":"reason3","label":"推荐理由3","type":"text","required":true},{"name":"verdict","label":"总结","type":"text","required":true}]', 'text', 'bar-chart', 96, 1, 2, 88, 1),

('TPL_VIRAL_003', 'viral-clone', '抖音种草文案', '抖音风格短视频配文', '抖音种草配文 - {{product_name}}：\n\n🔥 文案风格: {{style}}\n📹 适用视频内容: {{video_content}}\n📝 文案:\n\"{{main_text}}\"\n\n#话题标签: {{hashtags}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"style","label":"文案风格","type":"select","options":["反转惊喜型","干货教学型","情感共鸣型","搞笑娱乐型","悬念揭秘型"]},{"name":"video_content","label":"视频内容简述","type":"text","required":true,"placeholder":"如：产品展示+使用教程"},{"name":"main_text","label":"文案内容要求","type":"text","required":true,"placeholder":"如：先制造焦虑→引出产品→解决问题→限时优惠"},{"name":"hashtags","label":"话题要求","type":"text","required":false,"placeholder":"如：电商带货 好物推荐 新品首发"}]', 'text', 'music', 94, 1, 2, 76, 1),

('TPL_VIRAL_004', 'viral-clone', 'FB/Ins种草帖', 'Facebook/Instagram产品推荐帖', '{{platform}} Product Post - {{product_name}}：\n\n📸 Photo/Reel Idea: {{visual_idea}}\n✍️ Caption: {{caption_style}}\n💬 Engaging Hook: {{hook}}\n📖 Story Highlights: {{key_benefit}}\n🛒 CTA: {{cta}}\n#️⃣ Hashtags: {{hashtags}}', '[{"name":"product_name","label":"Product Name","type":"text","required":true},{"name":"platform","label":"Platform","type":"select","options":["Instagram","Facebook","Pinterest"]},{"name":"visual_idea","label":"Visual Idea","type":"text","required":true,"placeholder":"e.g. Before/After shot, Flat lay with props"},{"name":"caption_style","label":"Caption Style","type":"select","options":["Storytelling","Problem-Solution","Lifestyle","Educational"]},{"name":"hook","label":"Hook","type":"text","required":true,"placeholder":"e.g. This changed my morning routine forever"},{"name":"key_benefit","label":"Key Benefit","type":"text","required":true},{"name":"cta","label":"CTA","type":"select","options":["Link in bio","Shop now","DM to order","Tag a friend"]},{"name":"hashtags","label":"Hashtags","type":"text","required":true,"placeholder":"e.g. #skincare #beauty #selfcare"}]', 'text', 'instagram', 92, 1, 2, 54, 1),

('TPL_VIRAL_005', 'viral-clone', '知乎好物推荐', '知乎风格专业产品推荐', '知乎好物推荐 - {{product_name}}：\n\n❓ 问题: {{question}}\n📝 开头: {{opening}}\n🔍 专业分析: {{analysis}}\n📊 对比数据: {{data}}\n✅ 购买建议: {{advice}}\n🔗 好物卡片: {{product_name}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"question","label":"回答的问题","type":"text","required":true,"placeholder":"如：2025年有什么值得买的XX？"},{"name":"opening","label":"开头","type":"select","options":["用了3年的人来答...","作为XX行业从业者...","实测对比了10款...","千万别瞎买！先看这篇"]},{"name":"analysis","label":"专业分析角度","type":"text","required":true,"placeholder":"如：从材质/工艺/使用场景分析"},{"name":"data","label":"数据支撑","type":"text","required":true,"placeholder":"如：实验室测试数据、市场销量排名"},{"name":"advice","label":"购买建议","type":"text","required":true,"placeholder":"如：预算充足选A，性价比选B"}]', 'text', 'help-circle', 90, 1, 2, 42, 1),

('TPL_VIRAL_006', 'viral-clone', '公众号种草文', '微信公众号长文种草模板', '公众号种草 - {{product_name}}：\n\n📌 标题: {{title}}\n🎵 头图+引导语: {{opening_hook}}\n📖 正文结构({{words}}字):\n  1. 痛点共鸣: {{pain_hook}}\n  2. 产品测评: {{review_detail}}\n  3. 使用教程: {{tutorial}}\n  4. 福利引导: {{offer}}\n📲 转化: {{convert_action}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"title","label":"标题","type":"text","required":true,"placeholder":"如：用了3个月的XX，我决定把家里的都换掉"},{"name":"opening_hook","label":"开头钩子","type":"text","required":true},{"name":"words","label":"字数","type":"select","options":["1500","2500","4000"]},{"name":"pain_hook","label":"痛点共鸣","type":"text","required":true},{"name":"review_detail","label":"产品测评细节","type":"text","required":true},{"name":"tutorial","label":"使用教程/技巧","type":"text","required":true},{"name":"offer","label":"福利引导","type":"text","required":true,"placeholder":"如：新人专享价+赠品"},{"name":"convert_action","label":"转化动作","type":"select","options":["阅读原文跳转","扫码下单","加微信领取","小程序直达"]}]', 'text', 'file-text', 88, 1, 2, 35, 1),

('TPL_VIRAL_007', 'viral-clone', '微博好物分享', '微博140字短文案+九宫格', '微博好物种草 - {{product_name}}：\n\n📝 微博正文(140字内): {{short_text}}\n🖼 配图风格: {{image_style}}\n🔗 链接设置: {{link_type}}\n#️⃣ 话题: {{topics}}\n@ 互动: {{mention}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"short_text","label":"微博正文","type":"text","required":true,"placeholder":"如：最近挖到宝藏了！这个XX简直拯救了我的选择困难症"},{"name":"image_style","label":"配图风格","type":"select","options":["九宫格实拍","手拿产品自拍","环境氛围图","开箱过程图","效果对比图"]},{"name":"link_type","label":"链接设置","type":"select","options":["官网链接","淘宝客链接","小程序卡片","无链接纯种草"]},{"name":"topics","label":"话题","type":"text","required":true,"placeholder":"如：#好物推荐# #生活好物#"},{"name":"mention","label":"@互动","type":"text","required":false,"placeholder":"如：@品牌官微 @好物分享君"}]', 'text', 'twitter', 86, 1, 2, 29, 1),

('TPL_VIRAL_008', 'viral-clone', '买家秀引导文案', '引导买家写出优质评价+晒图', '买家秀引导 - {{product_name}}：\n\n🎁 激励方式: {{incentive}}\n📸 晒图要求: {{photo_req}}\n✍️ 文案引导:\n  {{guide_text}}\n📋 评价模板参考:\n  {{template_example}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"incentive","label":"激励方式","type":"select","options":["好评返现","晒图有礼","抽奖","积分奖励","VIP升级"]},{"name":"photo_req","label":"晒图要求","type":"select","options":["3张以上实拍","带场景使用图","视频+图片","细节特写","上身/上脸效果"]},{"name":"guide_text","label":"引导文案","type":"text","required":true,"placeholder":"如：亲收到还满意吗~帮我们拍个美美的买家秀呗"},{"name":"template_example","label":"模板参考要求","type":"text","required":true,"placeholder":"如：包含材质描述、使用感受、推荐人群"}]', 'text', 'camera', 84, 1, 2, 48, 1),

('TPL_VIRAL_009', 'viral-clone', 'KOL合作Brief', '达人合作Brief/产品介绍稿', 'KOL合作Brief - {{product_name}}：\n\n📋 品牌: {{brand}}\n🎯 产品: {{product_name}}\n💡 核心卖点(3个): {{key_selling}}\n📖 内容方向: {{content_angle}}\n⚠️ 必须提及: {{must_mention}}\n🚫 避免提及: {{avoid}}\n📸 视觉要求: {{visual_req}}\n📅 发布要求: {{post_req}}', '[{"name":"brand","label":"品牌名","type":"text","required":true},{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"key_selling","label":"核心卖点(3个)","type":"text","required":true,"placeholder":"如：1.纯天然成分 2.24h续航 3.30天无理由"},{"name":"content_angle","label":"内容角度","type":"select","options":["真实体验分享","教程/How-to","测评对比","生活场景","开箱惊喜"]},{"name":"must_mention","label":"必须提及","type":"text","required":true},{"name":"avoid","label":"避免提及","type":"text","required":false,"placeholder":"如：竞品名、具体价格"},{"name":"visual_req","label":"视觉要求","type":"text","required":true,"placeholder":"如：明亮自然光、产品占比30%以上"},{"name":"post_req","label":"发布要求","type":"text","required":true,"placeholder":"如：发布后保留30天以上、带#品牌话题"}]', 'text', 'users', 82, 1, 2, 38, 1),

('TPL_VIRAL_010', 'viral-clone', '评论区互动文案', '种草帖评论区引导/互动话术', '评论区互动 - {{product_name}}：\n\n🎯 引导目的: {{goal}}\n💬 互动话术({{count}}条):\n  风格: {{tone}}\n  要点: {{key_points}}\n  避免硬广感，自然种草', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"goal","label":"目的","type":"select","options":["引导问链接","引导留评论","引导转发@好友","解决疑虑","晒单返图"]},{"name":"count","label":"话术条数","type":"select","options":["5","10","15"]},{"name":"tone","label":"话术风格","type":"select","options":["路人真实安利","已购用户分享","专业解答","幽默调侃","情感共鸣"]},{"name":"key_points","label":"要点(逗号分隔)","type":"text","required":true,"placeholder":"如：效果好,性价比高,回购多次"}]', 'text', 'message-square', 80, 1, 2, 62, 1);

-- ==================== 7. translate 翻译/本地化模板 (8个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_TRANS_001', 'translate', '跨境标题翻译', '商品标题多语言翻译+SEO优化', '将以下商品标题翻译为{{target_lang}}，并针对{{platform}}做SEO优化：\n\n原始标题: {{original_title}}\n\n要求:\n- 保留核心关键词: {{keywords}}\n- 适配{{platform}}标题长度限制({{char_limit}}字符)\n- 符合当地搜索习惯\n- 包含{{search_volume}}高频搜索词', '[{"name":"original_title","label":"原始标题","type":"text","required":true},{"name":"target_lang","label":"目标语言","type":"select","options":["English","日本語","한국어","Español","Français","Deutsch","ภาษาไทย","Tiếng Việt","Português","العربية"]},{"name":"platform","label":"目标平台","type":"select","options":["Amazon","Shopee","Lazada","eBay","AliExpress","Rakuten"]},{"name":"keywords","label":"核心关键词(逗号分隔)","type":"text","required":true},{"name":"char_limit","label":"字符限制","type":"select","options":["80","120","200"]},{"name":"search_volume","label":"搜索量等级","type":"select","options":["高(大词)","中(长尾词)","低(精准词)"]}]', 'text', 'globe', 98, 1, 2, 72, 1),

('TPL_TRANS_002', 'translate', '商品详情翻译', '详情页/产品描述多语言翻译', '将以下产品描述翻译为{{target_lang}}，适配{{market}}市场：\n\n原始描述: {{original_desc}}\n\n翻译要求:\n- {{tone}}语气\n- 保留所有技术参数准确性\n- 尺码/单位转换为当地制式\n- 文化适配: {{culture_note}}', '[{"name":"original_desc","label":"原始描述","type":"text","required":true},{"name":"target_lang","label":"目标语言","type":"select","options":["English","日本語","한국어","Español","Français","Deutsch","ไทย","Tiếng Việt"]},{"name":"market","label":"目标市场","type":"select","options":["美国","日本","韩国","东南亚","欧洲","中东"]},{"name":"tone","label":"语气","type":"select","options":["专业正式","亲切友好","高端奢华","年轻潮流","简洁实用"]},{"name":"culture_note","label":"文化适配说明","type":"text","required":false,"placeholder":"如：避免猪肉相关描述(中东)、用美式尺码"}]', 'text', 'file-text', 96, 1, 2, 58, 1),

('TPL_TRANS_003', 'translate', '电商话术本地化', '促销/客服话术跨文化本地化', '将以下电商话术本地化为{{target_market}}市场版本：\n\n原始话术: {{original_copy}}\n\n本地化要点:\n- 符合{{target_market}}消费者心理\n- 适配当地促销习惯(如: {{promo_style}})\n- 避免文化禁忌: {{taboo_note}}\n- 保持品牌调性: {{brand_tone}}', '[{"name":"original_copy","label":"原始话术","type":"text","required":true},{"name":"target_market","label":"目标市场","type":"select","options":["美国","日本","韩国","东南亚","欧洲","中东","拉美"]},{"name":"promo_style","label":"当地促销习惯","type":"select","options":["直接打折(Discount %)","满减(Buy X Save Y)","买赠(BOGO)","包邮(Free Shipping)","限时闪购(Flash Sale)"]},{"name":"taboo_note","label":"文化禁忌说明","type":"text","required":false,"placeholder":"如：日本避免直接催促、中东避免女性形象"},{"name":"brand_tone","label":"品牌调性","type":"select","options":["专业高端","年轻活力","温暖走心","极简克制","幽默风趣"]}]', 'text', 'message-circle', 94, 1, 2, 43, 1),

('TPL_TRANS_004', 'translate', '评论区翻译', '用户评价/评论多语言翻译', '将买家评论从{{source_lang}}翻译为{{target_lang}}：\n\n评论原文: {{review_text}}\n\n要求:\n- 保留情感色彩({{sentiment}})\n- 口语化自然\n- 如有俚语/缩写，转为对应语言的口语表达\n- 保留emoji: {{keep_emoji}}', '[{"name":"review_text","label":"评论原文","type":"text","required":true},{"name":"source_lang","label":"源语言","type":"select","options":["中文","English","日本語","한국어","ไทย"]},{"name":"target_lang","label":"目标语言","type":"select","options":["中文","English","日本語","한국어","ไทย","Español"]},{"name":"sentiment","label":"情感色彩","type":"select","options":["正面(开心/满意)","中性(客观/平淡)","负面(失望/愤怒)"]},{"name":"keep_emoji","label":"保留emoji","type":"select","options":["是","否"]}]', 'text', 'star', 90, 1, 2, 28, 1),

('TPL_TRANS_005', 'translate', '店铺页面翻译', 'Shop/Store Page多语言版本', '将店铺页面内容翻译为{{target_lang}}：\n\n店铺名: {{shop_name}}\n店铺公告: {{shop_announcement}}\n退货政策: {{return_policy}}\n\n要求: 符合{{platform}}平台规范，专业准确', '[{"name":"shop_name","label":"店铺名称","type":"text","required":true},{"name":"shop_announcement","label":"店铺公告","type":"text","required":true},{"name":"return_policy","label":"退货政策","type":"text","required":true},{"name":"target_lang","label":"目标语言","type":"select","options":["English","日本語","한국어","ไทย","Español"]},{"name":"platform","label":"平台","type":"select","options":["Amazon","Shopee","Lazada","eBay"]}]', 'text', 'home', 86, 1, 2, 22, 1),

('TPL_TRANS_006', 'translate', '短视频字幕翻译', '短视频字幕/配音多语言翻译', '将以下短视频文案翻译为{{target_lang}}，适配{{platform}}：\n\n原文案: {{script}}\n时长: {{duration}}秒\n\n翻译要求:\n- 每句不超过{{char_per_line}}字符(字幕适配)\n- 保留节奏感和口语化\n- 关键卖点词汇不翻译: {{keep_terms}}\n- 适配{{platform}}热门话术风格', '[{"name":"script","label":"短视频文案","type":"text","required":true},{"name":"duration","label":"视频时长(秒)","type":"select","options":["15","30","60","90"]},{"name":"target_lang","label":"目标语言","type":"select","options":["English","日本語","한국어","ไทย","Español"]},{"name":"platform","label":"平台","type":"select","options":["TikTok","YouTube Shorts","Instagram Reels"]},{"name":"char_per_line","label":"每行字符上限","type":"select","options":["20","30","40"]},{"name":"keep_terms","label":"保留原词(逗号分隔)","type":"text","required":false,"placeholder":"如：品牌名、核心技术词"}]', 'text', 'subtitles', 84, 1, 2, 35, 1),

('TPL_TRANS_007', 'translate', '多语言客服模板', '多语言客服自动回复模板', '{{scenario}}场景客服回复 - {{target_lang}}：\n\n用户问题类型: {{question_type}}\n回复策略: {{strategy}}\n品牌语气: {{tone}}\n\n生成{{count}}条回复模板', '[{"name":"scenario","label":"场景","type":"select","options":["售前咨询","物流查询","退换货","投诉处理","催好评","尺寸咨询"]},{"name":"target_lang","label":"目标语言","type":"select","options":["English","日本語","한국어","ไทย","Español"]},{"name":"question_type","label":"问题类型","type":"text","required":true,"placeholder":"如：Can I get a discount?"},{"name":"strategy","label":"回复策略","type":"select","options":["直接解答","委婉拒绝","引导下单","安抚情绪","提供替代方案"]},{"name":"tone","label":"品牌语气","type":"select","options":["专业礼貌","热情友好","简洁高效","温暖贴心"]},{"name":"count","label":"模板条数","type":"select","options":["3","5","8"]}]', 'text', 'headphones', 82, 1, 2, 31, 1),

('TPL_TRANS_008', 'translate', '主图文字翻译', '主图/详情图上文字多语言替换', '将产品主图上的文字翻译为{{target_lang}}：\n\n原图文字内容: {{image_text}}\n文字位置: {{position}}\n\n要求:\n- 翻译后长度与原文字接近(<{{max_chars}}字符)\n- 保持营销感\n- 适合{{platform}}平台风格', '[{"name":"image_text","label":"图片文字","type":"text","required":true},{"name":"target_lang","label":"目标语言","type":"select","options":["English","日本語","한국어","ไทย","Español"]},{"name":"position","label":"文字位置","type":"select","options":["顶部","底部","居中","角标","侧边"]},{"name":"max_chars","label":"字符上限","type":"select","options":["10","20","30"]},{"name":"platform","label":"目标平台","type":"select","options":["Amazon","Shopee","Lazada","eBay"]}]', 'text', 'type', 80, 1, 2, 25, 1);

-- ==================== 8. creative 创意广告模板 (8个) ====================
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_CREATIVE_001', 'creative', '痛点解决方案广告', '痛点→解决方案型创意广告', '痛点方案广告 - {{product_name}}：\n\n😫 痛点画面: {{pain_scene}}\n💡 解决方案: {{solution_intro}}\n✨ {{product_name}}如何解决:\n  1. {{solve1}}\n  2. {{solve2}}\n  3. {{solve3}}\n🎯 行动号召: {{cta}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"pain_scene","label":"痛点场景描述","type":"text","required":true,"placeholder":"如：下雨天鞋子湿透、一身狼狈"},{"name":"solution_intro","label":"方案引入","type":"text","required":true,"placeholder":"如：一双会呼吸的防水鞋"},{"name":"solve1","label":"解决方案1","type":"text","required":true},{"name":"solve2","label":"解决方案2","type":"text","required":true},{"name":"solve3","label":"解决方案3","type":"text","required":true},{"name":"cta","label":"转化引导","type":"select","options":["告别XX烦恼","现在就试","3天无效退款","百万用户的选择"]}]', 'text', 'target', 98, 1, 2, 68, 1),

('TPL_CREATIVE_002', 'creative', '对比反差广告', 'Before/After对比型创意广告', 'Before/After广告 - {{product_name}}：\n\n❌ BEFORE(使用前): {{before_desc}}\n✅ AFTER(使用{{duration}}后): {{after_desc}}\n🔬 变化原理: {{principle}}\n📸 视觉呈现: {{visual_contrast}}\n💰 行动号召: {{cta}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"before_desc","label":"使用前描述","type":"text","required":true,"placeholder":"如：皮肤暗沉、毛孔粗大"},{"name":"duration","label":"使用时长","type":"select","options":["7天","14天","28天","立即"]},{"name":"after_desc","label":"使用后效果","type":"text","required":true,"placeholder":"如：肤色提亮、毛孔细腻"},{"name":"principle","label":"变化原理","type":"text","required":true,"placeholder":"如：烟酰胺阻断黑色素转移"},{"name":"visual_contrast","label":"视觉对比","type":"select","options":["左右对比","遮罩擦除","分屏展示","逐渐过渡"]},{"name":"cta","label":"行动号召","type":"select","options":["立即体验","限时优惠","免费试用","立即购买"]}]', 'text', 'columns', 96, 1, 2, 82, 1),

('TPL_CREATIVE_003', 'creative', '用户证言广告', '真实用户口碑/证言型广告', '用户证言广告 - {{product_name}}：\n\n👤 用户画像: {{user_profile}}\n💬 使用体验: {{testimony}}\n⭐ 评分: {{rating}}颗星\n📊 使用数据: {{data}\n🎁 专属福利: {{offer}}\n📲 行动指引: {{cta}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"user_profile","label":"用户画像","type":"text","required":true,"placeholder":"如：28岁宝妈、职场新人、健身教练"},{"name":"testimony","label":"用户证言","type":"text","required":true,"placeholder":"如：用了2周，同事都问我换了什么护肤品"},{"name":"rating","label":"评分","type":"select","options":["4.5","5"]},{"name":"data","label":"使用数据","type":"text","required":false,"placeholder":"如：已回购3次、推荐了5个朋友"},{"name":"offer","label":"专属福利","type":"text","required":true},{"name":"cta","label":"行动指引","type":"select","options":["加入百万用户","限时领取试用装","跟TA一样变美","加入购物车"]}]', 'text', 'thumbs-up', 94, 1, 2, 56, 1),

('TPL_CREATIVE_004', 'creative', '悬念/好奇心广告', '悬念揭晓型创意广告', '悬念广告 - {{product_name}}：\n\n🔮 悬念开头: {{teaser}}\n❓ 引发好奇: {{curiosity_hook}}\n🎭 揭晓答案: {{reveal}}\n✨ 核心价值: {{value_prop}}\n🎯 转化引导: {{cta}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"teaser","label":"悬念开头","type":"text","required":true,"placeholder":"如：这个东西99%的人都没见过..."},{"name":"curiosity_hook","label":"好奇钩子","type":"text","required":true,"placeholder":"如：但用过的人都把之前的扔了"},{"name":"reveal","label":"揭晓方式","type":"select","options":["直接揭晓","逐步揭晓","反转","由用户猜测→揭晓"]},{"name":"value_prop","label":"核心价值","type":"text","required":true},{"name":"cta","label":"转化引导","type":"select","options":["你猜对了吗","来一探究竟","马上试试","限时体验"]}]', 'text', 'help-circle', 92, 1, 2, 45, 1),

('TPL_CREATIVE_005', 'creative', '情感共鸣广告', '情感/故事驱动型广告', '情感广告 - {{product_name}}：\n\n❤️ 情感触发: {{emotion_trigger}}\n📖 故事核心: {{story_core}}\n👤 人物/场景: {{character}}\n💡 产品角色: {{product_role}}\n✨ 升华点: {{climax}}\n🎯 品牌共鸣: {{brand_message}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"emotion_trigger","label":"情感触发","type":"select","options":["母爱","父爱","友情","爱情","思乡","奋斗","成长","感恩"]},{"name":"story_core","label":"故事核心","type":"text","required":true,"placeholder":"如：妈妈的一双手、深夜加班的那盏灯"},{"name":"character","label":"人物/场景","type":"text","required":true},{"name":"product_role","label":"产品在故事中的角色","type":"select","options":["情感载体","问题解决者","陪伴者","见证者"]},{"name":"climax","label":"升华点","type":"text","required":true},{"name":"brand_message","label":"品牌信息","type":"text","required":true,"placeholder":"如：XX品牌，守护每一份爱"}]', 'text', 'heart', 90, 1, 2, 39, 1),

('TPL_CREATIVE_006', 'creative', '幽默/趣味广告', '幽默搞笑风格创意广告', '趣味广告 - {{product_name}}：\n\n😂 幽默角度: {{humor_angle}}\n🎭 表现手法: {{execution}}\n📝 核心梗: {{punchline}}\n🎯 产品植入: {{product_placement}}\n📲 转化引导: {{cta}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"humor_angle","label":"幽默角度","type":"select","options":["夸张放大","反转误会","自黑自嘲","生活吐槽","冷幽默","沙雕创意"]},{"name":"execution","label":"表现手法","type":"select","options":["情景短剧","表情包式","配音恶搞","对比反差","动画夸张"]},{"name":"punchline","label":"核心笑点/梗","type":"text","required":true},{"name":"product_placement","label":"产品植入方式","type":"select","options":["自然融入剧情","结尾反转露出","全程核心道具","字幕/口播带出"]},{"name":"cta","label":"转化引导","type":"select","options":["笑完别忘了下单","搞笑是认真的,效果也是","戳链接get同款"]}]', 'text', 'smile', 88, 1, 2, 52, 1),

('TPL_CREATIVE_007', 'creative', '数据/权威广告', '数据驱动/权威背书型广告', '权威背书广告 - {{product_name}}：\n\n📊 核心数据: {{key_data}}\n🏆 认证/背书: {{certification}}\n🔬 技术原理: {{tech_principle}}\n📈 市场表现: {{market_data}}\n🎯 信任强化: {{trust_element}}\n📲 行动号召: {{cta}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"key_data","label":"核心数据","type":"text","required":true,"placeholder":"如：97%用户28天肤色提亮、续航实测72小时"},{"name":"certification","label":"认证/背书","type":"text","required":true,"placeholder":"如：SGS认证、XX机构推荐、XX明星同款"},{"name":"tech_principle","label":"技术原理","type":"text","required":true,"placeholder":"如：第3代纳米微晶技术"},{"name":"market_data","label":"市场表现","type":"text","required":true,"placeholder":"如：天猫类目TOP3、累计销售100万+件"},{"name":"trust_element","label":"信任强化","type":"select","options":["30天无理由","终身质保","假一赔十","实验室报告"]},{"name":"cta","label":"行动号召","type":"select","options":["数据说话,实力圈粉","查看完整检测报告","加入百万用户"]}]', 'text', 'award', 86, 1, 2, 44, 1),

('TPL_CREATIVE_008', 'creative', '场景痛点广告', '场景化痛点触发+即时解决', '场景痛点广告 - {{product_name}}：\n\n🏠 场景: {{scene}}\n😣 痛点时刻: {{pain_moment}}\n⏱ 产品介入: {{intervention}}\n✨ 即时效果: {{instant_result}}\n💡 核心认知: {{insight}}\n📲 行动引导: {{cta}}', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"scene","label":"场景","type":"text","required":true,"placeholder":"如：重要会议前5分钟、第一次约会"},{"name":"pain_moment","label":"痛点时刻","type":"text","required":true,"placeholder":"如：发现衣服皱巴巴没法穿"},{"name":"intervention","label":"产品介入方式","type":"text","required":true,"placeholder":"如：拿出便携挂烫机30秒抚平"},{"name":"instant_result","label":"即时效果","type":"text","required":true},{"name":"insight","label":"核心认知","type":"text","required":true,"placeholder":"如：精致不是花时间，是用对工具"},{"name":"cta","label":"行动引导","type":"select","options":["别让细节毁了重要时刻","随身携带的秘密武器","点击拥有同款"]}]', 'text', 'zap', 84, 1, 2, 37, 1);
