-- B2 提示词模板 Mock 种子数据
INSERT INTO prompt_template (template_code, category, title, description, content, variables, model_type, icon, sort_order, is_public, status, usage_count, creator_id) VALUES
('TPL_MAIN_001', 'main_image', '电商通用主图', '适用于服装、饰品等白底商品主图生成，含场景化描述', '你是一个专业的电商商品图设计AI。请为{{product_name}}生成一张高质量商品主图，要求：\n1. 纯白背景，{{product_name}}位于画面{{position}}\n2. 采用{{lighting}}布光，突出商品质感\n3. 分辨率2048x2048，细节清晰\n4. 风格：{{style}}', '[{"name":"product_name","label":"商品名称","type":"text","required":true,"placeholder":"如：夏季连衣裙"},{"name":"position","label":"商品位置","type":"select","required":false,"placeholder":"居中/偏左/偏右","options":["居中","偏左","偏右"]},{"name":"lighting","label":"灯光风格","type":"select","required":false,"placeholder":"柔光/硬光/侧光","options":["柔光","硬光","侧光"]},{"name":"style","label":"整体风格","type":"select","required":false,"placeholder":"简约/时尚/奢华","options":["简约","时尚","奢华","清新"]}]', 'image', 'star', 100, 1, 2, 128, 1),

('TPL_MAIN_002', 'main_image', '美妆产品主图', '适用于护肤品、化妆品等产品，强调光泽和质感', '为{{product_name}}生成电商主图。{{product_name}}是一款{{product_type}}，主打{{selling_point}}。\n要求：渐变背景({{bg_color}})，产品居中放置，突出包装质感和液体光泽。', '[{"name":"product_name","label":"产品名称","type":"text","required":true,"placeholder":"如：保湿精华液"},{"name":"product_type","label":"产品类型","type":"text","required":true,"placeholder":"如：精华/面霜/口红"},{"name":"selling_point","label":"卖点","type":"text","required":true,"placeholder":"如：深层补水"},{"name":"bg_color","label":"背景色系","type":"select","required":false,"placeholder":"粉色/蓝色/金色","options":["粉色渐变","蓝色渐变","金色渐变","紫色渐变"]}]', 'image', 'palette', 95, 1, 2, 86, 1),

('TPL_SCENE_001', 'scene', '服装场景穿搭', '将商品融合到生活场景中，自然展示效果', '将{{product_name}}穿在模特身上，放置在{{scene_type}}场景中。模特姿势自然{{pose}}，光线为{{time_of_day}}，整体氛围{{mood}}。保持商品细节真实，融合度自然。', '[{"name":"product_name","label":"商品名称","type":"text","required":true,"placeholder":"如：条纹衬衫"},{"name":"scene_type","label":"场景类型","type":"select","required":true,"placeholder":"选择场景","options":["咖啡馆","街头","海滩","办公室","花园"]},{"name":"pose","label":"模特姿势","type":"text","required":false,"placeholder":"如：自然站立看向远方"},{"name":"time_of_day","label":"时间","type":"select","required":false,"placeholder":"选择时间","options":["上午","午后","傍晚","室内灯光"]},{"name":"mood","label":"氛围","type":"select","required":false,"placeholder":"选择氛围","options":["温暖","清新","高级感","活力"]}]', 'image', 'image', 90, 1, 2, 95, 1),

('TPL_SCENE_002', 'scene', '家居产品场景', '将家居用品融入真实家居环境中', '为{{product_name}}生成一张家居场景图。场景为{{room_type}}，风格为{{decor_style}}，{{product_name}}自然地放置在{{placement}}位置。画面温暖自然，分辨率4K。', '[{"name":"product_name","label":"商品名称","type":"text","required":true,"placeholder":"如：北欧风台灯"},{"name":"room_type","label":"房间类型","type":"select","required":true,"options":["客厅","卧室","书房","餐厅","阳台"]},{"name":"decor_style","label":"装修风格","type":"select","required":true,"options":["北欧简约","日式原木","现代轻奢","美式复古"]},{"name":"placement","label":"摆放位置","type":"select","required":true,"options":["床头柜","茶几","书桌","餐桌","角落"]}]', 'image', 'home', 85, 1, 2, 63, 1),

('TPL_VIDEO_001', 'video', '服装展示短视频', '15秒服装展示短视频，凸显商品动态效果', '为{{product_name}}生成15秒短视频脚本：\n前3秒：特写{{highlight_1}}\n3-8秒：模特穿着{{product_name}}在{{scene}}中{{action}}\n8-12秒：多角度旋转展示细节\n12-15秒：呈现品牌logo和{{slogan}}\n\n节奏感强，适合抖音/快手投放。', '[{"name":"product_name","label":"商品名称","type":"text","required":true,"placeholder":"如：宽松卫衣"},{"name":"highlight_1","label":"开场亮点","type":"text","required":true,"placeholder":"如：领口绣花细节"},{"name":"scene","label":"场景","type":"select","required":true,"options":["街头","校园","商场","公园"]},{"name":"action","label":"动作描述","type":"text","required":true,"placeholder":"如：轻松漫步转身"},{"name":"slogan","label":"slogan","type":"text","required":true,"placeholder":"如：自在，不设限"}]', 'video', 'video', 80, 1, 2, 45, 1),

('TPL_SCRIPT_001', 'script', '带货口播脚本', '适用于直播带货的完整口播脚本模板', '你是一位有{{years}}年经验的带货主播。请为{{product_name}}写一份{{duration}}分钟的带货口播脚本，产品卖点：{{selling_points}}，目标人群：{{target_audience}}，价格：{{price}}元。\n\n脚本结构：\n1. 开场引流（制造好奇）\n2. 痛点挖掘（用户为什么需要）\n3. 产品展示（卖点逐一呈现）\n4. 信任背书（好评/销量/资质）\n5. 限时福利（紧迫感促下单）\n\n语气：{{tone}}', '[{"name":"product_name","label":"商品名称","type":"text","required":true},{"name":"years","label":"主播经验","type":"select","required":false,"options":["3","5","10"]},{"name":"duration","label":"时长(分钟)","type":"select","required":true,"options":["3","5","10","15"]},{"name":"selling_points","label":"核心卖点","type":"text","required":true,"placeholder":"如：防水、防刮、超轻"},{"name":"target_audience","label":"目标人群","type":"text","required":true,"placeholder":"如：25-35岁职场女性"},{"name":"price","label":"价格(元)","type":"text","required":true,"placeholder":"如：99"},{"name":"tone","label":"语气风格","type":"select","required":false,"options":["亲切自然","专业权威","幽默搞笑","激情澎湃"]}]', 'text', 'mic', 75, 1, 2, 112, 1),

('TPL_SCRIPT_002', 'script', '小红书种草文案', '适用于小红书平台的种草内容模板', '请为{{product_name}}撰写一篇小红书种草笔记。\n产品：{{product_name}}\n价格：{{price}}元\n亮点：{{highlights}}\n个人使用感受：{{feeling}}\n\n要求：\n- 标题要有吸引力，使用emoji\n- 正文口语化，接地气\n- 穿插3-5个使用场景\n- 结尾附话题标签\n- 总字数300-500字', '[{"name":"product_name","label":"商品名称","type":"text","required":true},{"name":"price","label":"价格(元)","type":"text","required":true},{"name":"highlights","label":"产品亮点","type":"text","required":true,"placeholder":"如：持妆12小时不脱妆"},{"name":"feeling","label":"使用感受","type":"text","required":true,"placeholder":"如：服帖自然 像天生好皮肤"}]', 'text', 'pen', 70, 1, 2, 89, 1),

('TPL_COPY_001', 'copy', '朋友圈营销文案', '适用于微信朋友圈的商品营销文案', '为{{product_name}}写一条朋友圈营销文案，{{occasion}}场景使用。\n\n字数：100-150字\n风格：{{style}}\n包含：痛点引入 + 产品亮点 + 用户好评感 + 行动引导\n必须使用emoji，但不超过5个', '[{"name":"product_name","label":"商品名称","type":"text","required":true},{"name":"occasion","label":"使用场景","type":"select","required":true,"options":["新品上架","限时活动","种草推荐","买家秀","节日促销"]},{"name":"style","label":"文案风格","type":"select","required":true,"options":["走心文","趣味风","专业范","闺蜜分享"]}]', 'text', 'chat', 65, 1, 2, 76, 1),

('TPL_VIRAL_001', 'viral-clone', '爆款视频复刻', '分析爆款视频脚本结构并复刻', '分析以下爆款视频的核心结构，为{{product_name}}复刻一个同风格脚本。\n\n爆款视频核心元素：\n- 前3秒钩子类型：{{hook_type}}\n- 叙事结构：{{narrative}}\n- 节奏风格：{{pace}}\n- 转化策略：{{conversion}}\n\n要求：保留原爆款节奏和情绪走向，替换产品和场景，不要逐帧抄袭。', '[{"name":"product_name","label":"商品名称","type":"text","required":true},{"name":"hook_type","label":"钩子类型","type":"select","required":true,"options":["反差点","好奇钩子","利益前置","情景共鸣","视觉冲击"]},{"name":"narrative","label":"叙事结构","type":"select","required":true,"options":["问题-解决方案","前后对比","开箱体验","使用教程","多人互动"]},{"name":"pace","label":"节奏风格","type":"select","required":true,"options":["快节奏卡点","慢节奏沉浸","叙事娓娓道来","搞笑反转"]},{"name":"conversion","label":"转化策略","type":"select","required":true,"options":["限时优惠","赠品诱惑","社交认同","KOL背书"]}]', 'video', 'trending', 60, 1, 2, 42, 1),

-- 以下为待审核/草稿状态的模板
('TPL_DRAFT_001', 'main_image', '3C数码产品主图', '适用于手机壳、耳机、充电宝等数码产品', '为{{product_name}}生成科技感产品主图。深色科技背景，{{product_name}}悬浮展示，搭配{{light_effect}}光效。', '[{"name":"product_name","label":"产品名称","type":"text","required":true},{"name":"light_effect","label":"光效","type":"select","required":true,"options":["霓虹灯","粒子光效","激光线条","简约光晕"]}]', 'image', 'cpu', 50, 1, 1, 0, 1),

('TPL_DRAFT_002', 'script', '抖音直播预告文案', '适用于直播预热引流', '为{{product_name}}的直播写一条预告文案。直播时间{{live_time}}，主打{{theme}}，福利{{benefit}}。风格：{{style}}', '[{"name":"product_name","label":"商品名称","type":"text","required":true},{"name":"live_time","label":"直播时间","type":"text","required":true,"placeholder":"如：本周五晚8点"},{"name":"theme","label":"直播主题","type":"text","required":true,"placeholder":"如：夏季清仓"},{"name":"benefit","label":"福利","type":"text","required":true,"placeholder":"如：前100名下单送赠品"},{"name":"style","label":"风格","type":"select","required":true,"options":["悬念式","福利式","种草式"]}]', 'text', 'video', 45, 1, 0, 0, 1);

-- 提示词分组
INSERT INTO prompt_group (user_id, name, sort_order) VALUES
(1, '服装类', 1),
(1, '美妆类', 2),
(1, '常用模板', 3);

-- 提示词收藏
INSERT INTO prompt_favorite (user_id, template_id, group_id) VALUES
(1, 1, 1),
(1, 3, 1),
(1, 6, 3),
(1, 2, 2),
(1, 5, 3);
